// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <QJProtocolBuffers/ProtocolBuffers.h>

@class LoginRequest;
@class LoginResult;

@interface LoginRequest : QJPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasLoginId;
@property (readonly) BOOL hasPassword;
@property (nonatomic,strong) NSString* loginId;
@property (nonatomic,strong) NSString* password;
@end

@interface LoginResult : QJPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasResultCode;
@property (readonly) BOOL hasResultMsg;
@property (readonly) BOOL hasSessionId;
@property (readonly) BOOL hasUserId;
@property (readonly) BOOL hasHeadIconUrl;
@property (readonly) BOOL hasMobileNo;
@property (readonly) BOOL hasUserName;
@property (readonly) BOOL hasNickName;
@property (readonly) BOOL hasRecommendCode;
@property (nonatomic,strong) NSString* resultCode;
@property (nonatomic,strong) NSString* resultMsg;
@property (nonatomic,strong) NSString* sessionId;
@property (nonatomic,strong) NSString* userId;
@property (nonatomic,strong) NSString* headIconUrl;
@property (nonatomic,strong) NSString* mobileNo;
@property (nonatomic,strong) NSString* userName;
@property (nonatomic,strong) NSString* nickName;
@property (nonatomic,strong) NSString* recommendCode;
@end

