// Code generated by Wire-Lite protocol buffer compiler, do not edit.
// Source file: ///home/admin/protobuf/src/820a5f5a3a92aed2bf3ed535e5fbcca8/proto/SearchHot
package com.qjoy.basjoo.core.model.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 获取搜索热点
 */
public final class SearchWayInfo extends Message {

  public static final int TAG_CODE = 1;
  public static final int TAG_SHOWNAME = 2;

  public static final String DEFAULT_CODE = "";
  public static final String DEFAULT_SHOWNAME = "";

  /**
   * 背后的code，（上报服务端）
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public String code;

  /**
   * 显示的名称
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public String showName;

  public SearchWayInfo(SearchWayInfo message) {
    super(message);
    if (message == null) return;
    this.code = message.code;
    this.showName = message.showName;
  }

  public SearchWayInfo() {
  }

  public SearchWayInfo fillTagValue(int tag, Object value) {
    switch(tag) {
        case TAG_CODE:
        this.code = (String)value;
        break;
        case TAG_SHOWNAME:
        this.showName = (String)value;
        break;
        default: break;
        };
    return this;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SearchWayInfo)) return false;
    SearchWayInfo o = (SearchWayInfo) other;
    return equals(code, o.code)
        && equals(showName, o.showName);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = code != null ? code.hashCode() : 0;
      result = result * 37 + (showName != null ? showName.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }
}
