// Code generated by Wire-Lite protocol buffer compiler, do not edit.
// Source file: ///home/admin/protobuf/src/fd5db16300abed243be25b1f20df81aa/proto/RegisterUser
package com.qjoy.basjoo.core.model.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 注册请求
 */
public final class RegisterRequest extends Message {

  public static final int TAG_MOBILENO = 1;
  public static final int TAG_CHECKCODE = 2;
  public static final int TAG_PASSWORD = 3;
  public static final int TAG_HEADICONURL = 4;
  public static final int TAG_RECOMMENDCODE = 5;

  public static final String DEFAULT_MOBILENO = "";
  public static final String DEFAULT_CHECKCODE = "";
  public static final String DEFAULT_PASSWORD = "";
  public static final String DEFAULT_HEADICONURL = "";
  public static final String DEFAULT_RECOMMENDCODE = "";

  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public String mobileNo;

  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public String checkCode;

  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public String password;

  @ProtoField(tag = 4, type = STRING)
  public String headIconUrl;

  @ProtoField(tag = 5, type = STRING)
  public String recommendCode;

  public RegisterRequest(RegisterRequest message) {
    super(message);
    if (message == null) return;
    this.mobileNo = message.mobileNo;
    this.checkCode = message.checkCode;
    this.password = message.password;
    this.headIconUrl = message.headIconUrl;
    this.recommendCode = message.recommendCode;
  }

  public RegisterRequest() {
  }

  public RegisterRequest fillTagValue(int tag, Object value) {
    switch(tag) {
        case TAG_MOBILENO:
        this.mobileNo = (String)value;
        break;
        case TAG_CHECKCODE:
        this.checkCode = (String)value;
        break;
        case TAG_PASSWORD:
        this.password = (String)value;
        break;
        case TAG_HEADICONURL:
        this.headIconUrl = (String)value;
        break;
        case TAG_RECOMMENDCODE:
        this.recommendCode = (String)value;
        break;
        default: break;
        };
    return this;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RegisterRequest)) return false;
    RegisterRequest o = (RegisterRequest) other;
    return equals(mobileNo, o.mobileNo)
        && equals(checkCode, o.checkCode)
        && equals(password, o.password)
        && equals(headIconUrl, o.headIconUrl)
        && equals(recommendCode, o.recommendCode);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = mobileNo != null ? mobileNo.hashCode() : 0;
      result = result * 37 + (checkCode != null ? checkCode.hashCode() : 0);
      result = result * 37 + (password != null ? password.hashCode() : 0);
      result = result * 37 + (headIconUrl != null ? headIconUrl.hashCode() : 0);
      result = result * 37 + (recommendCode != null ? recommendCode.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }
}
