// Code generated by Wire-Lite protocol buffer compiler, do not edit.
// Source file: ///home/admin/protobuf/src/a955ef220d2efc3228333bbe1c4a864d/proto/Product
package com.qjoy.basjoo.core.model.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 颜色信息
 */
public final class ColorInfo extends Message {

  public static final int TAG_COLORCODE = 1;
  public static final int TAG_COLORNAME = 2;

  public static final String DEFAULT_COLORCODE = "";
  public static final String DEFAULT_COLORNAME = "";

  /**
   * 颜色编号
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public String colorCode;

  /**
   * 颜色名称
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public String colorName;

  public ColorInfo(ColorInfo message) {
    super(message);
    if (message == null) return;
    this.colorCode = message.colorCode;
    this.colorName = message.colorName;
  }

  public ColorInfo() {
  }

  public ColorInfo fillTagValue(int tag, Object value) {
    switch(tag) {
        case TAG_COLORCODE:
        this.colorCode = (String)value;
        break;
        case TAG_COLORNAME:
        this.colorName = (String)value;
        break;
        default: break;
        };
    return this;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ColorInfo)) return false;
    ColorInfo o = (ColorInfo) other;
    return equals(colorCode, o.colorCode)
        && equals(colorName, o.colorName);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = colorCode != null ? colorCode.hashCode() : 0;
      result = result * 37 + (colorName != null ? colorName.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }
}
