// Code generated by Wire-Lite protocol buffer compiler, do not edit.
// Source file: ///home/admin/protobuf/src/a955ef220d2efc3228333bbe1c4a864d/proto/Product
package com.qjoy.basjoo.core.model.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 成色信息
 */
public final class QualityInfo extends Message {

  public static final int TAG_QUALITYCODE = 1;
  public static final int TAG_QUALITYNAME = 2;

  public static final String DEFAULT_QUALITYCODE = "";
  public static final String DEFAULT_QUALITYNAME = "";

  /**
   * 成色编码：10 全新，0非全新，后续可能会有9，8，7，6，5，4，3，2，1，以及 8.5 ，7.5等code
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public String qualityCode;

  /**
   * 成色显示名称：如：全新，非全新，九成新，八成新
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public String qualityName;

  public QualityInfo(QualityInfo message) {
    super(message);
    if (message == null) return;
    this.qualityCode = message.qualityCode;
    this.qualityName = message.qualityName;
  }

  public QualityInfo() {
  }

  public QualityInfo fillTagValue(int tag, Object value) {
    switch(tag) {
        case TAG_QUALITYCODE:
        this.qualityCode = (String)value;
        break;
        case TAG_QUALITYNAME:
        this.qualityName = (String)value;
        break;
        default: break;
        };
    return this;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof QualityInfo)) return false;
    QualityInfo o = (QualityInfo) other;
    return equals(qualityCode, o.qualityCode)
        && equals(qualityName, o.qualityName);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = qualityCode != null ? qualityCode.hashCode() : 0;
      result = result * 37 + (qualityName != null ? qualityName.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }
}
