// Code generated by Wire-Lite protocol buffer compiler, do not edit.
// Source file: ///home/admin/protobuf/src/a955ef220d2efc3228333bbe1c4a864d/proto/Product
package com.qjoy.basjoo.core.model.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.DOUBLE;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 短租信息
 */
public final class ShortRentInfo extends Message {

  public static final int TAG_RENTCODE = 1;
  public static final int TAG_RENTPERIOD = 2;
  public static final int TAG_RENTPRICE = 3;
  public static final int TAG_TOTALRENTPRICE = 4;

  public static final String DEFAULT_RENTCODE = "";
  public static final String DEFAULT_RENTPERIOD = "";
  public static final Double DEFAULT_RENTPRICE = 0D;
  public static final Double DEFAULT_TOTALRENTPRICE = 0D;

  /**
   * 租金编码
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public String rentCode;

  /**
   * 周期，单位：天
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public String rentPeriod;

  /**
   * 折算后的单天价，单位 元/天
   */
  @ProtoField(tag = 3, type = DOUBLE, label = REQUIRED)
  public Double rentPrice;

  /**
   * 该周期内总价
   */
  @ProtoField(tag = 4, type = DOUBLE, label = REQUIRED)
  public Double totalRentPrice;

  public ShortRentInfo(ShortRentInfo message) {
    super(message);
    if (message == null) return;
    this.rentCode = message.rentCode;
    this.rentPeriod = message.rentPeriod;
    this.rentPrice = message.rentPrice;
    this.totalRentPrice = message.totalRentPrice;
  }

  public ShortRentInfo() {
  }

  public ShortRentInfo fillTagValue(int tag, Object value) {
    switch(tag) {
        case TAG_RENTCODE:
        this.rentCode = (String)value;
        break;
        case TAG_RENTPERIOD:
        this.rentPeriod = (String)value;
        break;
        case TAG_RENTPRICE:
        this.rentPrice = (Double)value;
        break;
        case TAG_TOTALRENTPRICE:
        this.totalRentPrice = (Double)value;
        break;
        default: break;
        };
    return this;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ShortRentInfo)) return false;
    ShortRentInfo o = (ShortRentInfo) other;
    return equals(rentCode, o.rentCode)
        && equals(rentPeriod, o.rentPeriod)
        && equals(rentPrice, o.rentPrice)
        && equals(totalRentPrice, o.totalRentPrice);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = rentCode != null ? rentCode.hashCode() : 0;
      result = result * 37 + (rentPeriod != null ? rentPeriod.hashCode() : 0);
      result = result * 37 + (rentPrice != null ? rentPrice.hashCode() : 0);
      result = result * 37 + (totalRentPrice != null ? totalRentPrice.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }
}
