// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestPb

package com.qjoy.basjoo.core.model.pb;

public final class TestPb {
  private TestPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtoResultTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qjoy.basjoo.core.model.pb.ProtoResultTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool is_success = 1;</code>
     */
    boolean hasIsSuccess();
    /**
     * <code>optional bool is_success = 1;</code>
     */
    boolean getIsSuccess();

    /**
     * <code>required string result_code = 2;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required string result_code = 2;</code>
     */
    java.lang.String getResultCode();
    /**
     * <code>required string result_code = 2;</code>
     */
    com.google.protobuf.ByteString
        getResultCodeBytes();

    /**
     * <code>required string result_message = 3;</code>
     */
    boolean hasResultMessage();
    /**
     * <code>required string result_message = 3;</code>
     */
    java.lang.String getResultMessage();
    /**
     * <code>required string result_message = 3;</code>
     */
    com.google.protobuf.ByteString
        getResultMessageBytes();
  }
  /**
   * Protobuf type {@code com.qjoy.basjoo.core.model.pb.ProtoResultTest}
   */
  public static final class ProtoResultTest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.qjoy.basjoo.core.model.pb.ProtoResultTest)
      ProtoResultTestOrBuilder {
    // Use ProtoResultTest.newBuilder() to construct.
    private ProtoResultTest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoResultTest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoResultTest defaultInstance;
    public static ProtoResultTest getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoResultTest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoResultTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isSuccess_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              resultCode_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              resultMessage_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qjoy.basjoo.core.model.pb.TestPb.internal_static_com_qjoy_basjoo_core_model_pb_ProtoResultTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qjoy.basjoo.core.model.pb.TestPb.internal_static_com_qjoy_basjoo_core_model_pb_ProtoResultTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest.class, com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoResultTest> PARSER =
        new com.google.protobuf.AbstractParser<ProtoResultTest>() {
      public ProtoResultTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoResultTest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoResultTest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IS_SUCCESS_FIELD_NUMBER = 1;
    private boolean isSuccess_;
    /**
     * <code>optional bool is_success = 1;</code>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool is_success = 1;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    public static final int RESULT_CODE_FIELD_NUMBER = 2;
    private java.lang.Object resultCode_;
    /**
     * <code>required string result_code = 2;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string result_code = 2;</code>
     */
    public java.lang.String getResultCode() {
      java.lang.Object ref = resultCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string result_code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResultCodeBytes() {
      java.lang.Object ref = resultCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_MESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object resultMessage_;
    /**
     * <code>required string result_message = 3;</code>
     */
    public boolean hasResultMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string result_message = 3;</code>
     */
    public java.lang.String getResultMessage() {
      java.lang.Object ref = resultMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string result_message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResultMessageBytes() {
      java.lang.Object ref = resultMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      isSuccess_ = false;
      resultCode_ = "";
      resultMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResultMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResultCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getResultMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResultCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getResultMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qjoy.basjoo.core.model.pb.ProtoResultTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qjoy.basjoo.core.model.pb.ProtoResultTest)
        com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qjoy.basjoo.core.model.pb.TestPb.internal_static_com_qjoy_basjoo_core_model_pb_ProtoResultTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qjoy.basjoo.core.model.pb.TestPb.internal_static_com_qjoy_basjoo_core_model_pb_ProtoResultTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest.class, com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest.Builder.class);
      }

      // Construct using com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        resultMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qjoy.basjoo.core.model.pb.TestPb.internal_static_com_qjoy_basjoo_core_model_pb_ProtoResultTest_descriptor;
      }

      public com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest getDefaultInstanceForType() {
        return com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest.getDefaultInstance();
      }

      public com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest build() {
        com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest buildPartial() {
        com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest result = new com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSuccess_ = isSuccess_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.resultMessage_ = resultMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest) {
          return mergeFrom((com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest other) {
        if (other == com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest.getDefaultInstance()) return this;
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.hasResultCode()) {
          bitField0_ |= 0x00000002;
          resultCode_ = other.resultCode_;
          onChanged();
        }
        if (other.hasResultMessage()) {
          bitField0_ |= 0x00000004;
          resultMessage_ = other.resultMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        if (!hasResultMessage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qjoy.basjoo.core.model.pb.TestPb.ProtoResultTest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isSuccess_ ;
      /**
       * <code>optional bool is_success = 1;</code>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool is_success = 1;</code>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>optional bool is_success = 1;</code>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_success = 1;</code>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object resultCode_ = "";
      /**
       * <code>required string result_code = 2;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string result_code = 2;</code>
       */
      public java.lang.String getResultCode() {
        java.lang.Object ref = resultCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string result_code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResultCodeBytes() {
        java.lang.Object ref = resultCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string result_code = 2;</code>
       */
      public Builder setResultCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string result_code = 2;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultCode_ = getDefaultInstance().getResultCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string result_code = 2;</code>
       */
      public Builder setResultCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resultMessage_ = "";
      /**
       * <code>required string result_message = 3;</code>
       */
      public boolean hasResultMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string result_message = 3;</code>
       */
      public java.lang.String getResultMessage() {
        java.lang.Object ref = resultMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string result_message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResultMessageBytes() {
        java.lang.Object ref = resultMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string result_message = 3;</code>
       */
      public Builder setResultMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        resultMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string result_message = 3;</code>
       */
      public Builder clearResultMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        resultMessage_ = getDefaultInstance().getResultMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string result_message = 3;</code>
       */
      public Builder setResultMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        resultMessage_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.qjoy.basjoo.core.model.pb.ProtoResultTest)
    }

    static {
      defaultInstance = new ProtoResultTest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.qjoy.basjoo.core.model.pb.ProtoResultTest)
  }

  public interface ProtoRequestTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qjoy.basjoo.core.model.pb.ProtoRequestTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string loginName = 1;</code>
     */
    boolean hasLoginName();
    /**
     * <code>required string loginName = 1;</code>
     */
    java.lang.String getLoginName();
    /**
     * <code>required string loginName = 1;</code>
     */
    com.google.protobuf.ByteString
        getLoginNameBytes();

    /**
     * <code>required string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code com.qjoy.basjoo.core.model.pb.ProtoRequestTest}
   */
  public static final class ProtoRequestTest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.qjoy.basjoo.core.model.pb.ProtoRequestTest)
      ProtoRequestTestOrBuilder {
    // Use ProtoRequestTest.newBuilder() to construct.
    private ProtoRequestTest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoRequestTest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoRequestTest defaultInstance;
    public static ProtoRequestTest getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoRequestTest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoRequestTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              loginName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qjoy.basjoo.core.model.pb.TestPb.internal_static_com_qjoy_basjoo_core_model_pb_ProtoRequestTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qjoy.basjoo.core.model.pb.TestPb.internal_static_com_qjoy_basjoo_core_model_pb_ProtoRequestTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest.class, com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoRequestTest> PARSER =
        new com.google.protobuf.AbstractParser<ProtoRequestTest>() {
      public ProtoRequestTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoRequestTest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoRequestTest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LOGINNAME_FIELD_NUMBER = 1;
    private java.lang.Object loginName_;
    /**
     * <code>required string loginName = 1;</code>
     */
    public boolean hasLoginName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string loginName = 1;</code>
     */
    public java.lang.String getLoginName() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string loginName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLoginNameBytes() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      loginName_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLoginName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLoginNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLoginNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qjoy.basjoo.core.model.pb.ProtoRequestTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qjoy.basjoo.core.model.pb.ProtoRequestTest)
        com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qjoy.basjoo.core.model.pb.TestPb.internal_static_com_qjoy_basjoo_core_model_pb_ProtoRequestTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qjoy.basjoo.core.model.pb.TestPb.internal_static_com_qjoy_basjoo_core_model_pb_ProtoRequestTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest.class, com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest.Builder.class);
      }

      // Construct using com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        loginName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qjoy.basjoo.core.model.pb.TestPb.internal_static_com_qjoy_basjoo_core_model_pb_ProtoRequestTest_descriptor;
      }

      public com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest getDefaultInstanceForType() {
        return com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest.getDefaultInstance();
      }

      public com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest build() {
        com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest buildPartial() {
        com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest result = new com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loginName_ = loginName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest) {
          return mergeFrom((com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest other) {
        if (other == com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest.getDefaultInstance()) return this;
        if (other.hasLoginName()) {
          bitField0_ |= 0x00000001;
          loginName_ = other.loginName_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLoginName()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qjoy.basjoo.core.model.pb.TestPb.ProtoRequestTest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object loginName_ = "";
      /**
       * <code>required string loginName = 1;</code>
       */
      public boolean hasLoginName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string loginName = 1;</code>
       */
      public java.lang.String getLoginName() {
        java.lang.Object ref = loginName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            loginName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string loginName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLoginNameBytes() {
        java.lang.Object ref = loginName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string loginName = 1;</code>
       */
      public Builder setLoginName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        loginName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string loginName = 1;</code>
       */
      public Builder clearLoginName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loginName_ = getDefaultInstance().getLoginName();
        onChanged();
        return this;
      }
      /**
       * <code>required string loginName = 1;</code>
       */
      public Builder setLoginNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        loginName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.qjoy.basjoo.core.model.pb.ProtoRequestTest)
    }

    static {
      defaultInstance = new ProtoRequestTest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.qjoy.basjoo.core.model.pb.ProtoRequestTest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qjoy_basjoo_core_model_pb_ProtoResultTest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qjoy_basjoo_core_model_pb_ProtoResultTest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qjoy_basjoo_core_model_pb_ProtoRequestTest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qjoy_basjoo_core_model_pb_ProtoRequestTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\006TestPb\022\035com.qjoy.basjoo.core.model.pb\"" +
      "R\n\017ProtoResultTest\022\022\n\nis_success\030\001 \001(\010\022\023" +
      "\n\013result_code\030\002 \002(\t\022\026\n\016result_message\030\003 " +
      "\002(\t\"7\n\020ProtoRequestTest\022\021\n\tloginName\030\001 \002" +
      "(\t\022\020\n\010password\030\002 \002(\tB\037\n\035com.qjoy.basjoo." +
      "core.model.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_qjoy_basjoo_core_model_pb_ProtoResultTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_qjoy_basjoo_core_model_pb_ProtoResultTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qjoy_basjoo_core_model_pb_ProtoResultTest_descriptor,
        new java.lang.String[] { "IsSuccess", "ResultCode", "ResultMessage", });
    internal_static_com_qjoy_basjoo_core_model_pb_ProtoRequestTest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_qjoy_basjoo_core_model_pb_ProtoRequestTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qjoy_basjoo_core_model_pb_ProtoRequestTest_descriptor,
        new java.lang.String[] { "LoginName", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
