// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "User.pb.h"

@implementation GetUserInfoRequest

- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GetUserInfoRequest*) parseFromData:(NSData*) data {
  GetUserInfoRequest* result = [[GetUserInfoRequest alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
    }
  }
}
@end


@implementation GetUserInfoResult

- (instancetype) init {
  if ((self = [super init])) {
    _resultCode = @"";
    _resultMsg = @"";
    _userId = @"";
    _headIconUrl = @"";
    _mobileNo = @"";
    _userName = @"";
    _inviteCode = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasResultCode) {
    [output writeString:1 value:self.resultCode];
  }
  if (self.hasResultMsg) {
    [output writeString:2 value:self.resultMsg];
  }
  if (self.hasUserId) {
    [output writeString:3 value:self.userId];
  }
  if (self.hasHeadIconUrl) {
    [output writeString:4 value:self.headIconUrl];
  }
  if (self.hasMobileNo) {
    [output writeString:5 value:self.mobileNo];
  }
  if (self.hasUserName) {
    [output writeString:6 value:self.userName];
  }
  if (self.hasInviteCode) {
    [output writeString:7 value:self.inviteCode];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasResultCode) {
    size_ += computeStringSize(1, self.resultCode);
  }
  if (self.hasResultMsg) {
    size_ += computeStringSize(2, self.resultMsg);
  }
  if (self.hasUserId) {
    size_ += computeStringSize(3, self.userId);
  }
  if (self.hasHeadIconUrl) {
    size_ += computeStringSize(4, self.headIconUrl);
  }
  if (self.hasMobileNo) {
    size_ += computeStringSize(5, self.mobileNo);
  }
  if (self.hasUserName) {
    size_ += computeStringSize(6, self.userName);
  }
  if (self.hasInviteCode) {
    size_ += computeStringSize(7, self.inviteCode);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GetUserInfoResult*) parseFromData:(NSData*) data {
  GetUserInfoResult* result = [[GetUserInfoResult alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasResultCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultCode", self.resultCode];
  }
  if (self.hasResultMsg) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultMsg", self.resultMsg];
  }
  if (self.hasUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userId", self.userId];
  }
  if (self.hasHeadIconUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"headIconUrl", self.headIconUrl];
  }
  if (self.hasMobileNo) {
    [output appendFormat:@"%@%@: %@\n", indent, @"mobileNo", self.mobileNo];
  }
  if (self.hasUserName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userName", self.userName];
  }
  if (self.hasInviteCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"inviteCode", self.inviteCode];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setResultCode:(NSString*) value {
  _hasResultCode = YES;
  _resultCode = value;
}
- (void) setResultMsg:(NSString*) value {
  _hasResultMsg = YES;
  _resultMsg = value;
}
- (void) setUserId:(NSString*) value {
  _hasUserId = YES;
  _userId = value;
}
- (void) setHeadIconUrl:(NSString*) value {
  _hasHeadIconUrl = YES;
  _headIconUrl = value;
}
- (void) setMobileNo:(NSString*) value {
  _hasMobileNo = YES;
  _mobileNo = value;
}
- (void) setUserName:(NSString*) value {
  _hasUserName = YES;
  _userName = value;
}
- (void) setInviteCode:(NSString*) value {
  _hasInviteCode = YES;
  _inviteCode = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setResultCode:[input readString]];
        break;
      }
      case 18: {
        [self setResultMsg:[input readString]];
        break;
      }
      case 26: {
        [self setUserId:[input readString]];
        break;
      }
      case 34: {
        [self setHeadIconUrl:[input readString]];
        break;
      }
      case 42: {
        [self setMobileNo:[input readString]];
        break;
      }
      case 50: {
        [self setUserName:[input readString]];
        break;
      }
      case 58: {
        [self setInviteCode:[input readString]];
        break;
      }
    }
  }
}
@end


