// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "GroupProduct.pb.h"

@implementation GetGroupProductListRequest

- (instancetype) init {
  if ((self = [super init])) {
    _startIndex = 0;
    _userId = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStartIndex) {
    [output writeInt32:1 value:self.startIndex];
  }
  if (self.hasUserId) {
    [output writeString:2 value:self.userId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasStartIndex) {
    size_ += computeInt32Size(1, self.startIndex);
  }
  if (self.hasUserId) {
    size_ += computeStringSize(2, self.userId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GetGroupProductListRequest*) parseFromData:(NSData*) data {
  GetGroupProductListRequest* result = [[GetGroupProductListRequest alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasStartIndex) {
    [output appendFormat:@"%@%@: %@\n", indent, @"startIndex", [NSNumber numberWithInteger:self.startIndex]];
  }
  if (self.hasUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userId", self.userId];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setStartIndex:(SInt32) value {
  _hasStartIndex = YES;
  _startIndex = value;
}
- (void) setUserId:(NSString*) value {
  _hasUserId = YES;
  _userId = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 8: {
        [self setStartIndex:[input readInt32]];
        break;
      }
      case 18: {
        [self setUserId:[input readString]];
        break;
      }
    }
  }
}
@end


@implementation GetGroupProductListResult

- (instancetype) init {
  if ((self = [super init])) {
    _resultCode = @"";
    _resultMsg = @"";
    _maxIndex = 0;
    _hasMore = NO;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasResultCode) {
    [output writeString:1 value:self.resultCode];
  }
  if (self.hasResultMsg) {
    [output writeString:2 value:self.resultMsg];
  }
  if (self.hasMaxIndex) {
    [output writeInt32:3 value:self.maxIndex];
  }
  if (self.hasHasMore) {
    [output writeBool:4 value:self.hasMore];
  }
  [self.groupProductLites enumerateObjectsUsingBlock:^(GroupProductLite *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:5 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasResultCode) {
    size_ += computeStringSize(1, self.resultCode);
  }
  if (self.hasResultMsg) {
    size_ += computeStringSize(2, self.resultMsg);
  }
  if (self.hasMaxIndex) {
    size_ += computeInt32Size(3, self.maxIndex);
  }
  if (self.hasHasMore) {
    size_ += computeBoolSize(4, self.hasMore);
  }
  [self.groupProductLites enumerateObjectsUsingBlock:^(GroupProductLite *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(5, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GetGroupProductListResult*) parseFromData:(NSData*) data {
  GetGroupProductListResult* result = [[GetGroupProductListResult alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasResultCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultCode", self.resultCode];
  }
  if (self.hasResultMsg) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultMsg", self.resultMsg];
  }
  if (self.hasMaxIndex) {
    [output appendFormat:@"%@%@: %@\n", indent, @"maxIndex", [NSNumber numberWithInteger:self.maxIndex]];
  }
  if (self.hasHasMore) {
    [output appendFormat:@"%@%@: %@\n", indent, @"hasMore", [NSNumber numberWithBool:self.hasMore]];
  }
  [self.groupProductLites enumerateObjectsUsingBlock:^(GroupProductLite *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"groupProductLites"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setResultCode:(NSString*) value {
  _hasResultCode = YES;
  _resultCode = value;
}
- (void) setResultMsg:(NSString*) value {
  _hasResultMsg = YES;
  _resultMsg = value;
}
- (void) setMaxIndex:(SInt32) value {
  _hasMaxIndex = YES;
  _maxIndex = value;
}
- (void) setHasMore:(BOOL) value {
  _hasHasMore = YES;
  _hasMore = value;
}
- (void)setGroupProductLitesArray:(NSArray *)array {
  _groupProductLites = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addGroupProductLites:(GroupProductLite*)value {
  if (_groupProductLites == nil) {
    _groupProductLites = [[NSMutableArray alloc]init];
  }
  [_groupProductLites addObject:value];
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setResultCode:[input readString]];
        break;
      }
      case 18: {
        [self setResultMsg:[input readString]];
        break;
      }
      case 24: {
        [self setMaxIndex:[input readInt32]];
        break;
      }
      case 32: {
        [self setHasMore:[input readBool]];
        break;
      }
      case 42: {
        GroupProductLite* sub = [[GroupProductLite alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addGroupProductLites:sub];
        break;
      }
    }
  }
}
@end


@implementation GroupProductLite

- (instancetype) init {
  if ((self = [super init])) {
    _productId = @"";
    _productType = @"";
    _promoType = 0;
    _brand = @"";
    _mainImageUrl = @"";
    _bannerImageUrl = @"";
    _title = @"";
    _desc = @"";
    _validStatus = 0;
    _validStartTime = 0L;
    _validEndTime = 0L;
    _serverTime = 0L;
    _minGroupCount = 0L;
    _discount = 0;
    _applyed = NO;
    _applyCount = 0L;
    _rentAmount = 0;
    _originalRentAmount = 0;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasProductId) {
    [output writeString:1 value:self.productId];
  }
  if (self.hasProductType) {
    [output writeString:2 value:self.productType];
  }
  if (self.hasPromoType) {
    [output writeInt32:3 value:self.promoType];
  }
  if (self.hasBrand) {
    [output writeString:4 value:self.brand];
  }
  if (self.hasMainImageUrl) {
    [output writeString:5 value:self.mainImageUrl];
  }
  if (self.hasBannerImageUrl) {
    [output writeString:6 value:self.bannerImageUrl];
  }
  if (self.hasTitle) {
    [output writeString:7 value:self.title];
  }
  if (self.hasDesc) {
    [output writeString:8 value:self.desc];
  }
  if (self.hasValidStatus) {
    [output writeInt32:9 value:self.validStatus];
  }
  if (self.hasValidStartTime) {
    [output writeInt64:10 value:self.validStartTime];
  }
  if (self.hasValidEndTime) {
    [output writeInt64:11 value:self.validEndTime];
  }
  if (self.hasServerTime) {
    [output writeInt64:12 value:self.serverTime];
  }
  if (self.hasMinGroupCount) {
    [output writeInt64:13 value:self.minGroupCount];
  }
  if (self.hasDiscount) {
    [output writeDouble:14 value:self.discount];
  }
  if (self.hasApplyed) {
    [output writeBool:15 value:self.applyed];
  }
  if (self.hasApplyCount) {
    [output writeInt64:16 value:self.applyCount];
  }
  if (self.hasRentAmount) {
    [output writeDouble:17 value:self.rentAmount];
  }
  if (self.hasOriginalRentAmount) {
    [output writeDouble:18 value:self.originalRentAmount];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasProductId) {
    size_ += computeStringSize(1, self.productId);
  }
  if (self.hasProductType) {
    size_ += computeStringSize(2, self.productType);
  }
  if (self.hasPromoType) {
    size_ += computeInt32Size(3, self.promoType);
  }
  if (self.hasBrand) {
    size_ += computeStringSize(4, self.brand);
  }
  if (self.hasMainImageUrl) {
    size_ += computeStringSize(5, self.mainImageUrl);
  }
  if (self.hasBannerImageUrl) {
    size_ += computeStringSize(6, self.bannerImageUrl);
  }
  if (self.hasTitle) {
    size_ += computeStringSize(7, self.title);
  }
  if (self.hasDesc) {
    size_ += computeStringSize(8, self.desc);
  }
  if (self.hasValidStatus) {
    size_ += computeInt32Size(9, self.validStatus);
  }
  if (self.hasValidStartTime) {
    size_ += computeInt64Size(10, self.validStartTime);
  }
  if (self.hasValidEndTime) {
    size_ += computeInt64Size(11, self.validEndTime);
  }
  if (self.hasServerTime) {
    size_ += computeInt64Size(12, self.serverTime);
  }
  if (self.hasMinGroupCount) {
    size_ += computeInt64Size(13, self.minGroupCount);
  }
  if (self.hasDiscount) {
    size_ += computeDoubleSize(14, self.discount);
  }
  if (self.hasApplyed) {
    size_ += computeBoolSize(15, self.applyed);
  }
  if (self.hasApplyCount) {
    size_ += computeInt64Size(16, self.applyCount);
  }
  if (self.hasRentAmount) {
    size_ += computeDoubleSize(17, self.rentAmount);
  }
  if (self.hasOriginalRentAmount) {
    size_ += computeDoubleSize(18, self.originalRentAmount);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GroupProductLite*) parseFromData:(NSData*) data {
  GroupProductLite* result = [[GroupProductLite alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasProductId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productId", self.productId];
  }
  if (self.hasProductType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productType", self.productType];
  }
  if (self.hasPromoType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"promoType", [NSNumber numberWithInteger:self.promoType]];
  }
  if (self.hasBrand) {
    [output appendFormat:@"%@%@: %@\n", indent, @"brand", self.brand];
  }
  if (self.hasMainImageUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"mainImageUrl", self.mainImageUrl];
  }
  if (self.hasBannerImageUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"bannerImageUrl", self.bannerImageUrl];
  }
  if (self.hasTitle) {
    [output appendFormat:@"%@%@: %@\n", indent, @"title", self.title];
  }
  if (self.hasDesc) {
    [output appendFormat:@"%@%@: %@\n", indent, @"desc", self.desc];
  }
  if (self.hasValidStatus) {
    [output appendFormat:@"%@%@: %@\n", indent, @"validStatus", [NSNumber numberWithInteger:self.validStatus]];
  }
  if (self.hasValidStartTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"validStartTime", [NSNumber numberWithLongLong:self.validStartTime]];
  }
  if (self.hasValidEndTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"validEndTime", [NSNumber numberWithLongLong:self.validEndTime]];
  }
  if (self.hasServerTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"serverTime", [NSNumber numberWithLongLong:self.serverTime]];
  }
  if (self.hasMinGroupCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"minGroupCount", [NSNumber numberWithLongLong:self.minGroupCount]];
  }
  if (self.hasDiscount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"discount", [NSNumber numberWithDouble:self.discount]];
  }
  if (self.hasApplyed) {
    [output appendFormat:@"%@%@: %@\n", indent, @"applyed", [NSNumber numberWithBool:self.applyed]];
  }
  if (self.hasApplyCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"applyCount", [NSNumber numberWithLongLong:self.applyCount]];
  }
  if (self.hasRentAmount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentAmount", [NSNumber numberWithDouble:self.rentAmount]];
  }
  if (self.hasOriginalRentAmount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"originalRentAmount", [NSNumber numberWithDouble:self.originalRentAmount]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setProductId:(NSString*) value {
  _hasProductId = YES;
  _productId = value;
}
- (void) setProductType:(NSString*) value {
  _hasProductType = YES;
  _productType = value;
}
- (void) setPromoType:(SInt32) value {
  _hasPromoType = YES;
  _promoType = value;
}
- (void) setBrand:(NSString*) value {
  _hasBrand = YES;
  _brand = value;
}
- (void) setMainImageUrl:(NSString*) value {
  _hasMainImageUrl = YES;
  _mainImageUrl = value;
}
- (void) setBannerImageUrl:(NSString*) value {
  _hasBannerImageUrl = YES;
  _bannerImageUrl = value;
}
- (void) setTitle:(NSString*) value {
  _hasTitle = YES;
  _title = value;
}
- (void) setDesc:(NSString*) value {
  _hasDesc = YES;
  _desc = value;
}
- (void) setValidStatus:(SInt32) value {
  _hasValidStatus = YES;
  _validStatus = value;
}
- (void) setValidStartTime:(SInt64) value {
  _hasValidStartTime = YES;
  _validStartTime = value;
}
- (void) setValidEndTime:(SInt64) value {
  _hasValidEndTime = YES;
  _validEndTime = value;
}
- (void) setServerTime:(SInt64) value {
  _hasServerTime = YES;
  _serverTime = value;
}
- (void) setMinGroupCount:(SInt64) value {
  _hasMinGroupCount = YES;
  _minGroupCount = value;
}
- (void) setDiscount:(Float64) value {
  _hasDiscount = YES;
  _discount = value;
}
- (void) setApplyed:(BOOL) value {
  _hasApplyed = YES;
  _applyed = value;
}
- (void) setApplyCount:(SInt64) value {
  _hasApplyCount = YES;
  _applyCount = value;
}
- (void) setRentAmount:(Float64) value {
  _hasRentAmount = YES;
  _rentAmount = value;
}
- (void) setOriginalRentAmount:(Float64) value {
  _hasOriginalRentAmount = YES;
  _originalRentAmount = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setProductId:[input readString]];
        break;
      }
      case 18: {
        [self setProductType:[input readString]];
        break;
      }
      case 24: {
        [self setPromoType:[input readInt32]];
        break;
      }
      case 34: {
        [self setBrand:[input readString]];
        break;
      }
      case 42: {
        [self setMainImageUrl:[input readString]];
        break;
      }
      case 50: {
        [self setBannerImageUrl:[input readString]];
        break;
      }
      case 58: {
        [self setTitle:[input readString]];
        break;
      }
      case 66: {
        [self setDesc:[input readString]];
        break;
      }
      case 72: {
        [self setValidStatus:[input readInt32]];
        break;
      }
      case 80: {
        [self setValidStartTime:[input readInt64]];
        break;
      }
      case 88: {
        [self setValidEndTime:[input readInt64]];
        break;
      }
      case 96: {
        [self setServerTime:[input readInt64]];
        break;
      }
      case 104: {
        [self setMinGroupCount:[input readInt64]];
        break;
      }
      case 113: {
        [self setDiscount:[input readDouble]];
        break;
      }
      case 120: {
        [self setApplyed:[input readBool]];
        break;
      }
      case 128: {
        [self setApplyCount:[input readInt64]];
        break;
      }
      case 137: {
        [self setRentAmount:[input readDouble]];
        break;
      }
      case 145: {
        [self setOriginalRentAmount:[input readDouble]];
        break;
      }
    }
  }
}
@end


@implementation GetGroupProductDetailRequest

- (instancetype) init {
  if ((self = [super init])) {
    _productId = @"";
    _userId = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasProductId) {
    [output writeString:1 value:self.productId];
  }
  if (self.hasUserId) {
    [output writeString:2 value:self.userId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasProductId) {
    size_ += computeStringSize(1, self.productId);
  }
  if (self.hasUserId) {
    size_ += computeStringSize(2, self.userId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GetGroupProductDetailRequest*) parseFromData:(NSData*) data {
  GetGroupProductDetailRequest* result = [[GetGroupProductDetailRequest alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasProductId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productId", self.productId];
  }
  if (self.hasUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userId", self.userId];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setProductId:(NSString*) value {
  _hasProductId = YES;
  _productId = value;
}
- (void) setUserId:(NSString*) value {
  _hasUserId = YES;
  _userId = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setProductId:[input readString]];
        break;
      }
      case 18: {
        [self setUserId:[input readString]];
        break;
      }
    }
  }
}
@end


@implementation GetGroupProductDetailResult

- (instancetype) init {
  if ((self = [super init])) {
    _resultCode = @"";
    _resultMsg = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasResultCode) {
    [output writeString:1 value:self.resultCode];
  }
  if (self.hasResultMsg) {
    [output writeString:2 value:self.resultMsg];
  }
  if (self.hasGroupProductDetail) {
    [output writeMessage:3 value:self.groupProductDetail];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasResultCode) {
    size_ += computeStringSize(1, self.resultCode);
  }
  if (self.hasResultMsg) {
    size_ += computeStringSize(2, self.resultMsg);
  }
  if (self.hasGroupProductDetail) {
    size_ += computeMessageSize(3, self.groupProductDetail);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GetGroupProductDetailResult*) parseFromData:(NSData*) data {
  GetGroupProductDetailResult* result = [[GetGroupProductDetailResult alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasResultCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultCode", self.resultCode];
  }
  if (self.hasResultMsg) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultMsg", self.resultMsg];
  }
  if (self.hasGroupProductDetail) {
    [output appendFormat:@"%@%@ {\n", indent, @"groupProductDetail"];
    [self.groupProductDetail writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setResultCode:(NSString*) value {
  _hasResultCode = YES;
  _resultCode = value;
}
- (void) setResultMsg:(NSString*) value {
  _hasResultMsg = YES;
  _resultMsg = value;
}
- (void) setGroupProductDetail:(GroupProductDetail*) value {
  _hasGroupProductDetail = YES;
  _groupProductDetail = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setResultCode:[input readString]];
        break;
      }
      case 18: {
        [self setResultMsg:[input readString]];
        break;
      }
      case 26: {
        GroupProductDetail* sub = [[GroupProductDetail alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self setGroupProductDetail:sub];
        break;
      }
    }
  }
}
@end


@implementation GroupProductDetail

- (instancetype) init {
  if ((self = [super init])) {
    _productId = @"";
    _productType = @"";
    _promoType = 0;
    _brand = @"";
    _mainImageUrl = @"";
    _bannerImageUrl = @"";
    _title = @"";
    _desc = @"";
    _validStatus = 0;
    _validStartTime = 0L;
    _validEndTime = 0L;
    _serverTime = 0L;
    _minGroupCount = 0L;
    _marketPrice = 0;
    _pledgeAmount = 0;
    _transFee = 0;
    _location = @"";
    _discount = 0;
    _applyed = NO;
    _applyCount = 0L;
    _rentAmount = 0;
    _originalRentAmount = 0;
    _rentPeriodName = @"";
    _rentAmountPerDay = 0;
    _rentAmountPerMonth = 0;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasProductId) {
    [output writeString:1 value:self.productId];
  }
  if (self.hasProductType) {
    [output writeString:2 value:self.productType];
  }
  if (self.hasPromoType) {
    [output writeInt32:3 value:self.promoType];
  }
  if (self.hasBrand) {
    [output writeString:4 value:self.brand];
  }
  if (self.hasMainImageUrl) {
    [output writeString:5 value:self.mainImageUrl];
  }
  if (self.hasBannerImageUrl) {
    [output writeString:6 value:self.bannerImageUrl];
  }
  if (self.hasTitle) {
    [output writeString:7 value:self.title];
  }
  if (self.hasDesc) {
    [output writeString:8 value:self.desc];
  }
  if (self.hasValidStatus) {
    [output writeInt32:9 value:self.validStatus];
  }
  if (self.hasValidStartTime) {
    [output writeInt64:10 value:self.validStartTime];
  }
  if (self.hasValidEndTime) {
    [output writeInt64:11 value:self.validEndTime];
  }
  if (self.hasServerTime) {
    [output writeInt64:12 value:self.serverTime];
  }
  if (self.hasMinGroupCount) {
    [output writeInt64:13 value:self.minGroupCount];
  }
  if (self.hasMarketPrice) {
    [output writeDouble:14 value:self.marketPrice];
  }
  if (self.hasPledgeAmount) {
    [output writeDouble:15 value:self.pledgeAmount];
  }
  if (self.hasTransFee) {
    [output writeDouble:16 value:self.transFee];
  }
  if (self.hasLocation) {
    [output writeString:17 value:self.location];
  }
  [self.categoryInfo enumerateObjectsUsingBlock:^(GroupProductCategory *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:18 value:element];
  }];
  [self.baseParam enumerateObjectsUsingBlock:^(GroupProductBaseParam *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:19 value:element];
  }];
  [self.imageParamUrls enumerateObjectsUsingBlock:^(NSString *element, NSUInteger idx, BOOL *stop) {
    [output writeString:20 value:element];
  }];
  if (self.hasDiscount) {
    [output writeDouble:21 value:self.discount];
  }
  if (self.hasApplyed) {
    [output writeBool:22 value:self.applyed];
  }
  if (self.hasApplyCount) {
    [output writeInt64:23 value:self.applyCount];
  }
  if (self.hasRentAmount) {
    [output writeDouble:24 value:self.rentAmount];
  }
  if (self.hasOriginalRentAmount) {
    [output writeDouble:25 value:self.originalRentAmount];
  }
  if (self.hasRentPeriodName) {
    [output writeString:26 value:self.rentPeriodName];
  }
  if (self.hasRentAmountPerDay) {
    [output writeDouble:27 value:self.rentAmountPerDay];
  }
  if (self.hasRentAmountPerMonth) {
    [output writeDouble:28 value:self.rentAmountPerMonth];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasProductId) {
    size_ += computeStringSize(1, self.productId);
  }
  if (self.hasProductType) {
    size_ += computeStringSize(2, self.productType);
  }
  if (self.hasPromoType) {
    size_ += computeInt32Size(3, self.promoType);
  }
  if (self.hasBrand) {
    size_ += computeStringSize(4, self.brand);
  }
  if (self.hasMainImageUrl) {
    size_ += computeStringSize(5, self.mainImageUrl);
  }
  if (self.hasBannerImageUrl) {
    size_ += computeStringSize(6, self.bannerImageUrl);
  }
  if (self.hasTitle) {
    size_ += computeStringSize(7, self.title);
  }
  if (self.hasDesc) {
    size_ += computeStringSize(8, self.desc);
  }
  if (self.hasValidStatus) {
    size_ += computeInt32Size(9, self.validStatus);
  }
  if (self.hasValidStartTime) {
    size_ += computeInt64Size(10, self.validStartTime);
  }
  if (self.hasValidEndTime) {
    size_ += computeInt64Size(11, self.validEndTime);
  }
  if (self.hasServerTime) {
    size_ += computeInt64Size(12, self.serverTime);
  }
  if (self.hasMinGroupCount) {
    size_ += computeInt64Size(13, self.minGroupCount);
  }
  if (self.hasMarketPrice) {
    size_ += computeDoubleSize(14, self.marketPrice);
  }
  if (self.hasPledgeAmount) {
    size_ += computeDoubleSize(15, self.pledgeAmount);
  }
  if (self.hasTransFee) {
    size_ += computeDoubleSize(16, self.transFee);
  }
  if (self.hasLocation) {
    size_ += computeStringSize(17, self.location);
  }
  [self.categoryInfo enumerateObjectsUsingBlock:^(GroupProductCategory *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(18, element);
  }];
  [self.baseParam enumerateObjectsUsingBlock:^(GroupProductBaseParam *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(19, element);
  }];
  {
    __block SInt32 dataSize = 0;
    const NSUInteger count = self.imageParamUrls.count;
    [self.imageParamUrls enumerateObjectsUsingBlock:^(NSString *element, NSUInteger idx, BOOL *stop) {
      dataSize += computeStringSizeNoTag(element);
    }];
    size_ += dataSize;
    size_ += (SInt32)(2 * count);
  }
  if (self.hasDiscount) {
    size_ += computeDoubleSize(21, self.discount);
  }
  if (self.hasApplyed) {
    size_ += computeBoolSize(22, self.applyed);
  }
  if (self.hasApplyCount) {
    size_ += computeInt64Size(23, self.applyCount);
  }
  if (self.hasRentAmount) {
    size_ += computeDoubleSize(24, self.rentAmount);
  }
  if (self.hasOriginalRentAmount) {
    size_ += computeDoubleSize(25, self.originalRentAmount);
  }
  if (self.hasRentPeriodName) {
    size_ += computeStringSize(26, self.rentPeriodName);
  }
  if (self.hasRentAmountPerDay) {
    size_ += computeDoubleSize(27, self.rentAmountPerDay);
  }
  if (self.hasRentAmountPerMonth) {
    size_ += computeDoubleSize(28, self.rentAmountPerMonth);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GroupProductDetail*) parseFromData:(NSData*) data {
  GroupProductDetail* result = [[GroupProductDetail alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasProductId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productId", self.productId];
  }
  if (self.hasProductType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productType", self.productType];
  }
  if (self.hasPromoType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"promoType", [NSNumber numberWithInteger:self.promoType]];
  }
  if (self.hasBrand) {
    [output appendFormat:@"%@%@: %@\n", indent, @"brand", self.brand];
  }
  if (self.hasMainImageUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"mainImageUrl", self.mainImageUrl];
  }
  if (self.hasBannerImageUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"bannerImageUrl", self.bannerImageUrl];
  }
  if (self.hasTitle) {
    [output appendFormat:@"%@%@: %@\n", indent, @"title", self.title];
  }
  if (self.hasDesc) {
    [output appendFormat:@"%@%@: %@\n", indent, @"desc", self.desc];
  }
  if (self.hasValidStatus) {
    [output appendFormat:@"%@%@: %@\n", indent, @"validStatus", [NSNumber numberWithInteger:self.validStatus]];
  }
  if (self.hasValidStartTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"validStartTime", [NSNumber numberWithLongLong:self.validStartTime]];
  }
  if (self.hasValidEndTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"validEndTime", [NSNumber numberWithLongLong:self.validEndTime]];
  }
  if (self.hasServerTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"serverTime", [NSNumber numberWithLongLong:self.serverTime]];
  }
  if (self.hasMinGroupCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"minGroupCount", [NSNumber numberWithLongLong:self.minGroupCount]];
  }
  if (self.hasMarketPrice) {
    [output appendFormat:@"%@%@: %@\n", indent, @"marketPrice", [NSNumber numberWithDouble:self.marketPrice]];
  }
  if (self.hasPledgeAmount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"pledgeAmount", [NSNumber numberWithDouble:self.pledgeAmount]];
  }
  if (self.hasTransFee) {
    [output appendFormat:@"%@%@: %@\n", indent, @"transFee", [NSNumber numberWithDouble:self.transFee]];
  }
  if (self.hasLocation) {
    [output appendFormat:@"%@%@: %@\n", indent, @"location", self.location];
  }
  [self.categoryInfo enumerateObjectsUsingBlock:^(GroupProductCategory *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"categoryInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.baseParam enumerateObjectsUsingBlock:^(GroupProductBaseParam *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"baseParam"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.imageParamUrls enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@: %@\n", indent, @"imageParamUrls", obj];
  }];
  if (self.hasDiscount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"discount", [NSNumber numberWithDouble:self.discount]];
  }
  if (self.hasApplyed) {
    [output appendFormat:@"%@%@: %@\n", indent, @"applyed", [NSNumber numberWithBool:self.applyed]];
  }
  if (self.hasApplyCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"applyCount", [NSNumber numberWithLongLong:self.applyCount]];
  }
  if (self.hasRentAmount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentAmount", [NSNumber numberWithDouble:self.rentAmount]];
  }
  if (self.hasOriginalRentAmount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"originalRentAmount", [NSNumber numberWithDouble:self.originalRentAmount]];
  }
  if (self.hasRentPeriodName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentPeriodName", self.rentPeriodName];
  }
  if (self.hasRentAmountPerDay) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentAmountPerDay", [NSNumber numberWithDouble:self.rentAmountPerDay]];
  }
  if (self.hasRentAmountPerMonth) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentAmountPerMonth", [NSNumber numberWithDouble:self.rentAmountPerMonth]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setProductId:(NSString*) value {
  _hasProductId = YES;
  _productId = value;
}
- (void) setProductType:(NSString*) value {
  _hasProductType = YES;
  _productType = value;
}
- (void) setPromoType:(SInt32) value {
  _hasPromoType = YES;
  _promoType = value;
}
- (void) setBrand:(NSString*) value {
  _hasBrand = YES;
  _brand = value;
}
- (void) setMainImageUrl:(NSString*) value {
  _hasMainImageUrl = YES;
  _mainImageUrl = value;
}
- (void) setBannerImageUrl:(NSString*) value {
  _hasBannerImageUrl = YES;
  _bannerImageUrl = value;
}
- (void) setTitle:(NSString*) value {
  _hasTitle = YES;
  _title = value;
}
- (void) setDesc:(NSString*) value {
  _hasDesc = YES;
  _desc = value;
}
- (void) setValidStatus:(SInt32) value {
  _hasValidStatus = YES;
  _validStatus = value;
}
- (void) setValidStartTime:(SInt64) value {
  _hasValidStartTime = YES;
  _validStartTime = value;
}
- (void) setValidEndTime:(SInt64) value {
  _hasValidEndTime = YES;
  _validEndTime = value;
}
- (void) setServerTime:(SInt64) value {
  _hasServerTime = YES;
  _serverTime = value;
}
- (void) setMinGroupCount:(SInt64) value {
  _hasMinGroupCount = YES;
  _minGroupCount = value;
}
- (void) setMarketPrice:(Float64) value {
  _hasMarketPrice = YES;
  _marketPrice = value;
}
- (void) setPledgeAmount:(Float64) value {
  _hasPledgeAmount = YES;
  _pledgeAmount = value;
}
- (void) setTransFee:(Float64) value {
  _hasTransFee = YES;
  _transFee = value;
}
- (void) setLocation:(NSString*) value {
  _hasLocation = YES;
  _location = value;
}
- (void)setCategoryInfoArray:(NSArray *)array {
  _categoryInfo = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addCategoryInfo:(GroupProductCategory*)value {
  if (_categoryInfo == nil) {
    _categoryInfo = [[NSMutableArray alloc]init];
  }
  [_categoryInfo addObject:value];
}
- (void)setBaseParamArray:(NSArray *)array {
  _baseParam = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addBaseParam:(GroupProductBaseParam*)value {
  if (_baseParam == nil) {
    _baseParam = [[NSMutableArray alloc]init];
  }
  [_baseParam addObject:value];
}
- (void)setImageParamUrlsArray:(NSArray *)array {
  _imageParamUrls = [[NSMutableArray alloc] initWithArray:array];
}
- (void)addImageParamUrls:(NSString*)value {
  if (_imageParamUrls == nil) {
    _imageParamUrls = [[NSMutableArray alloc]init];
  }
  [_imageParamUrls addObject:value];
}
- (void) setDiscount:(Float64) value {
  _hasDiscount = YES;
  _discount = value;
}
- (void) setApplyed:(BOOL) value {
  _hasApplyed = YES;
  _applyed = value;
}
- (void) setApplyCount:(SInt64) value {
  _hasApplyCount = YES;
  _applyCount = value;
}
- (void) setRentAmount:(Float64) value {
  _hasRentAmount = YES;
  _rentAmount = value;
}
- (void) setOriginalRentAmount:(Float64) value {
  _hasOriginalRentAmount = YES;
  _originalRentAmount = value;
}
- (void) setRentPeriodName:(NSString*) value {
  _hasRentPeriodName = YES;
  _rentPeriodName = value;
}
- (void) setRentAmountPerDay:(Float64) value {
  _hasRentAmountPerDay = YES;
  _rentAmountPerDay = value;
}
- (void) setRentAmountPerMonth:(Float64) value {
  _hasRentAmountPerMonth = YES;
  _rentAmountPerMonth = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setProductId:[input readString]];
        break;
      }
      case 18: {
        [self setProductType:[input readString]];
        break;
      }
      case 24: {
        [self setPromoType:[input readInt32]];
        break;
      }
      case 34: {
        [self setBrand:[input readString]];
        break;
      }
      case 42: {
        [self setMainImageUrl:[input readString]];
        break;
      }
      case 50: {
        [self setBannerImageUrl:[input readString]];
        break;
      }
      case 58: {
        [self setTitle:[input readString]];
        break;
      }
      case 66: {
        [self setDesc:[input readString]];
        break;
      }
      case 72: {
        [self setValidStatus:[input readInt32]];
        break;
      }
      case 80: {
        [self setValidStartTime:[input readInt64]];
        break;
      }
      case 88: {
        [self setValidEndTime:[input readInt64]];
        break;
      }
      case 96: {
        [self setServerTime:[input readInt64]];
        break;
      }
      case 104: {
        [self setMinGroupCount:[input readInt64]];
        break;
      }
      case 113: {
        [self setMarketPrice:[input readDouble]];
        break;
      }
      case 121: {
        [self setPledgeAmount:[input readDouble]];
        break;
      }
      case 129: {
        [self setTransFee:[input readDouble]];
        break;
      }
      case 138: {
        [self setLocation:[input readString]];
        break;
      }
      case 146: {
        GroupProductCategory* sub = [[GroupProductCategory alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addCategoryInfo:sub];
        break;
      }
      case 154: {
        GroupProductBaseParam* sub = [[GroupProductBaseParam alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addBaseParam:sub];
        break;
      }
      case 162: {
        [self addImageParamUrls:[input readString]];
        break;
      }
      case 169: {
        [self setDiscount:[input readDouble]];
        break;
      }
      case 176: {
        [self setApplyed:[input readBool]];
        break;
      }
      case 184: {
        [self setApplyCount:[input readInt64]];
        break;
      }
      case 193: {
        [self setRentAmount:[input readDouble]];
        break;
      }
      case 201: {
        [self setOriginalRentAmount:[input readDouble]];
        break;
      }
      case 210: {
        [self setRentPeriodName:[input readString]];
        break;
      }
      case 217: {
        [self setRentAmountPerDay:[input readDouble]];
        break;
      }
      case 225: {
        [self setRentAmountPerMonth:[input readDouble]];
        break;
      }
    }
  }
}
@end


@implementation GroupProductCategory

- (instancetype) init {
  if ((self = [super init])) {
    _categoryCode = @"";
    _categoryName = @"";
    _categoryImgUrl = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasCategoryCode) {
    [output writeString:1 value:self.categoryCode];
  }
  if (self.hasCategoryName) {
    [output writeString:2 value:self.categoryName];
  }
  if (self.hasCategoryImgUrl) {
    [output writeString:3 value:self.categoryImgUrl];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasCategoryCode) {
    size_ += computeStringSize(1, self.categoryCode);
  }
  if (self.hasCategoryName) {
    size_ += computeStringSize(2, self.categoryName);
  }
  if (self.hasCategoryImgUrl) {
    size_ += computeStringSize(3, self.categoryImgUrl);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GroupProductCategory*) parseFromData:(NSData*) data {
  GroupProductCategory* result = [[GroupProductCategory alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasCategoryCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"categoryCode", self.categoryCode];
  }
  if (self.hasCategoryName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"categoryName", self.categoryName];
  }
  if (self.hasCategoryImgUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"categoryImgUrl", self.categoryImgUrl];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setCategoryCode:(NSString*) value {
  _hasCategoryCode = YES;
  _categoryCode = value;
}
- (void) setCategoryName:(NSString*) value {
  _hasCategoryName = YES;
  _categoryName = value;
}
- (void) setCategoryImgUrl:(NSString*) value {
  _hasCategoryImgUrl = YES;
  _categoryImgUrl = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setCategoryCode:[input readString]];
        break;
      }
      case 18: {
        [self setCategoryName:[input readString]];
        break;
      }
      case 26: {
        [self setCategoryImgUrl:[input readString]];
        break;
      }
    }
  }
}
@end


@implementation GroupProductBaseParam

- (instancetype) init {
  if ((self = [super init])) {
    _code = @"";
    _showKey = @"";
    _showValue = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasCode) {
    [output writeString:1 value:self.code];
  }
  if (self.hasShowKey) {
    [output writeString:2 value:self.showKey];
  }
  if (self.hasShowValue) {
    [output writeString:3 value:self.showValue];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasCode) {
    size_ += computeStringSize(1, self.code);
  }
  if (self.hasShowKey) {
    size_ += computeStringSize(2, self.showKey);
  }
  if (self.hasShowValue) {
    size_ += computeStringSize(3, self.showValue);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GroupProductBaseParam*) parseFromData:(NSData*) data {
  GroupProductBaseParam* result = [[GroupProductBaseParam alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"code", self.code];
  }
  if (self.hasShowKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"showKey", self.showKey];
  }
  if (self.hasShowValue) {
    [output appendFormat:@"%@%@: %@\n", indent, @"showValue", self.showValue];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setCode:(NSString*) value {
  _hasCode = YES;
  _code = value;
}
- (void) setShowKey:(NSString*) value {
  _hasShowKey = YES;
  _showKey = value;
}
- (void) setShowValue:(NSString*) value {
  _hasShowValue = YES;
  _showValue = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setCode:[input readString]];
        break;
      }
      case 18: {
        [self setShowKey:[input readString]];
        break;
      }
      case 26: {
        [self setShowValue:[input readString]];
        break;
      }
    }
  }
}
@end


