// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Revert

package com.qjoy.basjoo.core.model.pb;

public final class Revert {
  private Revert() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetRevertDetailRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qjoy.basjoo.core.model.pb.GetRevertDetailRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string userId = 1;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required string userId = 1;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    java.lang.String getUserId();
    /**
     * <code>required string userId = 1;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>required string orderId = 2;</code>
     *
     * <pre>
     *订单ID
     * </pre>
     */
    boolean hasOrderId();
    /**
     * <code>required string orderId = 2;</code>
     *
     * <pre>
     *订单ID
     * </pre>
     */
    java.lang.String getOrderId();
    /**
     * <code>required string orderId = 2;</code>
     *
     * <pre>
     *订单ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();
  }
  /**
   * Protobuf type {@code com.qjoy.basjoo.core.model.pb.GetRevertDetailRequest}
   *
   * <pre>
   *获取归还详情
   * </pre>
   */
  public static final class GetRevertDetailRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.qjoy.basjoo.core.model.pb.GetRevertDetailRequest)
      GetRevertDetailRequestOrBuilder {
    // Use GetRevertDetailRequest.newBuilder() to construct.
    private GetRevertDetailRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetRevertDetailRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetRevertDetailRequest defaultInstance;
    public static GetRevertDetailRequest getDefaultInstance() {
      return defaultInstance;
    }

    public GetRevertDetailRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetRevertDetailRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              userId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              orderId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qjoy.basjoo.core.model.pb.Revert.internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qjoy.basjoo.core.model.pb.Revert.internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest.class, com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<GetRevertDetailRequest> PARSER =
        new com.google.protobuf.AbstractParser<GetRevertDetailRequest>() {
      public GetRevertDetailRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRevertDetailRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetRevertDetailRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    /**
     * <code>required string userId = 1;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userId = 1;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userId = 1;</code>
     *
     * <pre>
     *用户ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERID_FIELD_NUMBER = 2;
    private java.lang.Object orderId_;
    /**
     * <code>required string orderId = 2;</code>
     *
     * <pre>
     *订单ID
     * </pre>
     */
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string orderId = 2;</code>
     *
     * <pre>
     *订单ID
     * </pre>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string orderId = 2;</code>
     *
     * <pre>
     *订单ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userId_ = "";
      orderId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOrderIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOrderIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qjoy.basjoo.core.model.pb.GetRevertDetailRequest}
     *
     * <pre>
     *获取归还详情
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qjoy.basjoo.core.model.pb.GetRevertDetailRequest)
        com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qjoy.basjoo.core.model.pb.Revert.internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qjoy.basjoo.core.model.pb.Revert.internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest.class, com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest.Builder.class);
      }

      // Construct using com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qjoy.basjoo.core.model.pb.Revert.internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailRequest_descriptor;
      }

      public com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest getDefaultInstanceForType() {
        return com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest.getDefaultInstance();
      }

      public com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest build() {
        com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest buildPartial() {
        com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest result = new com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.orderId_ = orderId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest) {
          return mergeFrom((com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest other) {
        if (other == com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          bitField0_ |= 0x00000001;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasOrderId()) {
          bitField0_ |= 0x00000002;
          orderId_ = other.orderId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasOrderId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>required string userId = 1;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userId = 1;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userId = 1;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userId = 1;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 1;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string userId = 1;</code>
       *
       * <pre>
       *用户ID
       * </pre>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>required string orderId = 2;</code>
       *
       * <pre>
       *订单ID
       * </pre>
       */
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string orderId = 2;</code>
       *
       * <pre>
       *订单ID
       * </pre>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string orderId = 2;</code>
       *
       * <pre>
       *订单ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string orderId = 2;</code>
       *
       * <pre>
       *订单ID
       * </pre>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string orderId = 2;</code>
       *
       * <pre>
       *订单ID
       * </pre>
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>required string orderId = 2;</code>
       *
       * <pre>
       *订单ID
       * </pre>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        orderId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.qjoy.basjoo.core.model.pb.GetRevertDetailRequest)
    }

    static {
      defaultInstance = new GetRevertDetailRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.qjoy.basjoo.core.model.pb.GetRevertDetailRequest)
  }

  public interface GetRevertDetailResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.qjoy.basjoo.core.model.pb.GetRevertDetailResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string resultCode = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required string resultCode = 1;</code>
     */
    java.lang.String getResultCode();
    /**
     * <code>required string resultCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultCodeBytes();

    /**
     * <code>required string resultMsg = 2;</code>
     */
    boolean hasResultMsg();
    /**
     * <code>required string resultMsg = 2;</code>
     */
    java.lang.String getResultMsg();
    /**
     * <code>required string resultMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getResultMsgBytes();

    /**
     * <code>optional int32 orderStatus = 3;</code>
     */
    boolean hasOrderStatus();
    /**
     * <code>optional int32 orderStatus = 3;</code>
     */
    int getOrderStatus();

    /**
     * <code>optional int64 applyTime = 4;</code>
     *
     * <pre>
     *申请归还时间
     * </pre>
     */
    boolean hasApplyTime();
    /**
     * <code>optional int64 applyTime = 4;</code>
     *
     * <pre>
     *申请归还时间
     * </pre>
     */
    long getApplyTime();

    /**
     * <code>optional int64 revertTime = 5;</code>
     *
     * <pre>
     *完成归还时间
     * </pre>
     */
    boolean hasRevertTime();
    /**
     * <code>optional int64 revertTime = 5;</code>
     *
     * <pre>
     *完成归还时间
     * </pre>
     */
    long getRevertTime();

    /**
     * <code>repeated string evidentalImgs = 6;</code>
     *
     * <pre>
     *归还凭证图片
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getEvidentalImgsList();
    /**
     * <code>repeated string evidentalImgs = 6;</code>
     *
     * <pre>
     *归还凭证图片
     * </pre>
     */
    int getEvidentalImgsCount();
    /**
     * <code>repeated string evidentalImgs = 6;</code>
     *
     * <pre>
     *归还凭证图片
     * </pre>
     */
    java.lang.String getEvidentalImgs(int index);
    /**
     * <code>repeated string evidentalImgs = 6;</code>
     *
     * <pre>
     *归还凭证图片
     * </pre>
     */
    com.google.protobuf.ByteString
        getEvidentalImgsBytes(int index);

    /**
     * <code>optional string revertIntro = 7;</code>
     *
     * <pre>
     *归还说明
     * </pre>
     */
    boolean hasRevertIntro();
    /**
     * <code>optional string revertIntro = 7;</code>
     *
     * <pre>
     *归还说明
     * </pre>
     */
    java.lang.String getRevertIntro();
    /**
     * <code>optional string revertIntro = 7;</code>
     *
     * <pre>
     *归还说明
     * </pre>
     */
    com.google.protobuf.ByteString
        getRevertIntroBytes();

    /**
     * <code>optional string transportationId = 8;</code>
     *
     * <pre>
     *快递号
     * </pre>
     */
    boolean hasTransportationId();
    /**
     * <code>optional string transportationId = 8;</code>
     *
     * <pre>
     *快递号
     * </pre>
     */
    java.lang.String getTransportationId();
    /**
     * <code>optional string transportationId = 8;</code>
     *
     * <pre>
     *快递号
     * </pre>
     */
    com.google.protobuf.ByteString
        getTransportationIdBytes();

    /**
     * <code>optional string transportationCompany = 9;</code>
     *
     * <pre>
     *快递公司
     * </pre>
     */
    boolean hasTransportationCompany();
    /**
     * <code>optional string transportationCompany = 9;</code>
     *
     * <pre>
     *快递公司
     * </pre>
     */
    java.lang.String getTransportationCompany();
    /**
     * <code>optional string transportationCompany = 9;</code>
     *
     * <pre>
     *快递公司
     * </pre>
     */
    com.google.protobuf.ByteString
        getTransportationCompanyBytes();

    /**
     * <code>optional string transportationIntro = 10;</code>
     *
     * <pre>
     *物流说明
     * </pre>
     */
    boolean hasTransportationIntro();
    /**
     * <code>optional string transportationIntro = 10;</code>
     *
     * <pre>
     *物流说明
     * </pre>
     */
    java.lang.String getTransportationIntro();
    /**
     * <code>optional string transportationIntro = 10;</code>
     *
     * <pre>
     *物流说明
     * </pre>
     */
    com.google.protobuf.ByteString
        getTransportationIntroBytes();
  }
  /**
   * Protobuf type {@code com.qjoy.basjoo.core.model.pb.GetRevertDetailResult}
   *
   * <pre>
   *获取归还结果
   * </pre>
   */
  public static final class GetRevertDetailResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.qjoy.basjoo.core.model.pb.GetRevertDetailResult)
      GetRevertDetailResultOrBuilder {
    // Use GetRevertDetailResult.newBuilder() to construct.
    private GetRevertDetailResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetRevertDetailResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetRevertDetailResult defaultInstance;
    public static GetRevertDetailResult getDefaultInstance() {
      return defaultInstance;
    }

    public GetRevertDetailResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetRevertDetailResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              resultCode_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              resultMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              orderStatus_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              applyTime_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              revertTime_ = input.readInt64();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                evidentalImgs_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              evidentalImgs_.add(bs);
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              revertIntro_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              transportationId_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              transportationCompany_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              transportationIntro_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          evidentalImgs_ = evidentalImgs_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qjoy.basjoo.core.model.pb.Revert.internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qjoy.basjoo.core.model.pb.Revert.internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult.class, com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult.Builder.class);
    }

    public static com.google.protobuf.Parser<GetRevertDetailResult> PARSER =
        new com.google.protobuf.AbstractParser<GetRevertDetailResult>() {
      public GetRevertDetailResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRevertDetailResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetRevertDetailResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private java.lang.Object resultCode_;
    /**
     * <code>required string resultCode = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string resultCode = 1;</code>
     */
    public java.lang.String getResultCode() {
      java.lang.Object ref = resultCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string resultCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultCodeBytes() {
      java.lang.Object ref = resultCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULTMSG_FIELD_NUMBER = 2;
    private java.lang.Object resultMsg_;
    /**
     * <code>required string resultMsg = 2;</code>
     */
    public boolean hasResultMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string resultMsg = 2;</code>
     */
    public java.lang.String getResultMsg() {
      java.lang.Object ref = resultMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string resultMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResultMsgBytes() {
      java.lang.Object ref = resultMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERSTATUS_FIELD_NUMBER = 3;
    private int orderStatus_;
    /**
     * <code>optional int32 orderStatus = 3;</code>
     */
    public boolean hasOrderStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 orderStatus = 3;</code>
     */
    public int getOrderStatus() {
      return orderStatus_;
    }

    public static final int APPLYTIME_FIELD_NUMBER = 4;
    private long applyTime_;
    /**
     * <code>optional int64 applyTime = 4;</code>
     *
     * <pre>
     *申请归还时间
     * </pre>
     */
    public boolean hasApplyTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 applyTime = 4;</code>
     *
     * <pre>
     *申请归还时间
     * </pre>
     */
    public long getApplyTime() {
      return applyTime_;
    }

    public static final int REVERTTIME_FIELD_NUMBER = 5;
    private long revertTime_;
    /**
     * <code>optional int64 revertTime = 5;</code>
     *
     * <pre>
     *完成归还时间
     * </pre>
     */
    public boolean hasRevertTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 revertTime = 5;</code>
     *
     * <pre>
     *完成归还时间
     * </pre>
     */
    public long getRevertTime() {
      return revertTime_;
    }

    public static final int EVIDENTALIMGS_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList evidentalImgs_;
    /**
     * <code>repeated string evidentalImgs = 6;</code>
     *
     * <pre>
     *归还凭证图片
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getEvidentalImgsList() {
      return evidentalImgs_;
    }
    /**
     * <code>repeated string evidentalImgs = 6;</code>
     *
     * <pre>
     *归还凭证图片
     * </pre>
     */
    public int getEvidentalImgsCount() {
      return evidentalImgs_.size();
    }
    /**
     * <code>repeated string evidentalImgs = 6;</code>
     *
     * <pre>
     *归还凭证图片
     * </pre>
     */
    public java.lang.String getEvidentalImgs(int index) {
      return evidentalImgs_.get(index);
    }
    /**
     * <code>repeated string evidentalImgs = 6;</code>
     *
     * <pre>
     *归还凭证图片
     * </pre>
     */
    public com.google.protobuf.ByteString
        getEvidentalImgsBytes(int index) {
      return evidentalImgs_.getByteString(index);
    }

    public static final int REVERTINTRO_FIELD_NUMBER = 7;
    private java.lang.Object revertIntro_;
    /**
     * <code>optional string revertIntro = 7;</code>
     *
     * <pre>
     *归还说明
     * </pre>
     */
    public boolean hasRevertIntro() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string revertIntro = 7;</code>
     *
     * <pre>
     *归还说明
     * </pre>
     */
    public java.lang.String getRevertIntro() {
      java.lang.Object ref = revertIntro_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          revertIntro_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string revertIntro = 7;</code>
     *
     * <pre>
     *归还说明
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRevertIntroBytes() {
      java.lang.Object ref = revertIntro_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        revertIntro_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSPORTATIONID_FIELD_NUMBER = 8;
    private java.lang.Object transportationId_;
    /**
     * <code>optional string transportationId = 8;</code>
     *
     * <pre>
     *快递号
     * </pre>
     */
    public boolean hasTransportationId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string transportationId = 8;</code>
     *
     * <pre>
     *快递号
     * </pre>
     */
    public java.lang.String getTransportationId() {
      java.lang.Object ref = transportationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transportationId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string transportationId = 8;</code>
     *
     * <pre>
     *快递号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTransportationIdBytes() {
      java.lang.Object ref = transportationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transportationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSPORTATIONCOMPANY_FIELD_NUMBER = 9;
    private java.lang.Object transportationCompany_;
    /**
     * <code>optional string transportationCompany = 9;</code>
     *
     * <pre>
     *快递公司
     * </pre>
     */
    public boolean hasTransportationCompany() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string transportationCompany = 9;</code>
     *
     * <pre>
     *快递公司
     * </pre>
     */
    public java.lang.String getTransportationCompany() {
      java.lang.Object ref = transportationCompany_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transportationCompany_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string transportationCompany = 9;</code>
     *
     * <pre>
     *快递公司
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTransportationCompanyBytes() {
      java.lang.Object ref = transportationCompany_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transportationCompany_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSPORTATIONINTRO_FIELD_NUMBER = 10;
    private java.lang.Object transportationIntro_;
    /**
     * <code>optional string transportationIntro = 10;</code>
     *
     * <pre>
     *物流说明
     * </pre>
     */
    public boolean hasTransportationIntro() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string transportationIntro = 10;</code>
     *
     * <pre>
     *物流说明
     * </pre>
     */
    public java.lang.String getTransportationIntro() {
      java.lang.Object ref = transportationIntro_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          transportationIntro_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string transportationIntro = 10;</code>
     *
     * <pre>
     *物流说明
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTransportationIntroBytes() {
      java.lang.Object ref = transportationIntro_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transportationIntro_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      resultCode_ = "";
      resultMsg_ = "";
      orderStatus_ = 0;
      applyTime_ = 0L;
      revertTime_ = 0L;
      evidentalImgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      revertIntro_ = "";
      transportationId_ = "";
      transportationCompany_ = "";
      transportationIntro_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResultMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResultCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResultMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, orderStatus_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, applyTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, revertTime_);
      }
      for (int i = 0; i < evidentalImgs_.size(); i++) {
        output.writeBytes(6, evidentalImgs_.getByteString(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getRevertIntroBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getTransportationIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, getTransportationCompanyBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(10, getTransportationIntroBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResultMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, orderStatus_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, applyTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, revertTime_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < evidentalImgs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(evidentalImgs_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getEvidentalImgsList().size();
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getRevertIntroBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getTransportationIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getTransportationCompanyBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getTransportationIntroBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qjoy.basjoo.core.model.pb.GetRevertDetailResult}
     *
     * <pre>
     *获取归还结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.qjoy.basjoo.core.model.pb.GetRevertDetailResult)
        com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qjoy.basjoo.core.model.pb.Revert.internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qjoy.basjoo.core.model.pb.Revert.internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult.class, com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult.Builder.class);
      }

      // Construct using com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        resultMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        orderStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        applyTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        revertTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        evidentalImgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        revertIntro_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        transportationId_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        transportationCompany_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        transportationIntro_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qjoy.basjoo.core.model.pb.Revert.internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailResult_descriptor;
      }

      public com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult getDefaultInstanceForType() {
        return com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult.getDefaultInstance();
      }

      public com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult build() {
        com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult buildPartial() {
        com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult result = new com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultMsg_ = resultMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.orderStatus_ = orderStatus_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.applyTime_ = applyTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.revertTime_ = revertTime_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          evidentalImgs_ = evidentalImgs_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.evidentalImgs_ = evidentalImgs_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.revertIntro_ = revertIntro_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.transportationId_ = transportationId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.transportationCompany_ = transportationCompany_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.transportationIntro_ = transportationIntro_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult) {
          return mergeFrom((com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult other) {
        if (other == com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          bitField0_ |= 0x00000001;
          resultCode_ = other.resultCode_;
          onChanged();
        }
        if (other.hasResultMsg()) {
          bitField0_ |= 0x00000002;
          resultMsg_ = other.resultMsg_;
          onChanged();
        }
        if (other.hasOrderStatus()) {
          setOrderStatus(other.getOrderStatus());
        }
        if (other.hasApplyTime()) {
          setApplyTime(other.getApplyTime());
        }
        if (other.hasRevertTime()) {
          setRevertTime(other.getRevertTime());
        }
        if (!other.evidentalImgs_.isEmpty()) {
          if (evidentalImgs_.isEmpty()) {
            evidentalImgs_ = other.evidentalImgs_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureEvidentalImgsIsMutable();
            evidentalImgs_.addAll(other.evidentalImgs_);
          }
          onChanged();
        }
        if (other.hasRevertIntro()) {
          bitField0_ |= 0x00000040;
          revertIntro_ = other.revertIntro_;
          onChanged();
        }
        if (other.hasTransportationId()) {
          bitField0_ |= 0x00000080;
          transportationId_ = other.transportationId_;
          onChanged();
        }
        if (other.hasTransportationCompany()) {
          bitField0_ |= 0x00000100;
          transportationCompany_ = other.transportationCompany_;
          onChanged();
        }
        if (other.hasTransportationIntro()) {
          bitField0_ |= 0x00000200;
          transportationIntro_ = other.transportationIntro_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        if (!hasResultMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qjoy.basjoo.core.model.pb.Revert.GetRevertDetailResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object resultCode_ = "";
      /**
       * <code>required string resultCode = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string resultCode = 1;</code>
       */
      public java.lang.String getResultCode() {
        java.lang.Object ref = resultCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string resultCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultCodeBytes() {
        java.lang.Object ref = resultCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string resultCode = 1;</code>
       */
      public Builder setResultCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = getDefaultInstance().getResultCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string resultCode = 1;</code>
       */
      public Builder setResultCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resultMsg_ = "";
      /**
       * <code>required string resultMsg = 2;</code>
       */
      public boolean hasResultMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string resultMsg = 2;</code>
       */
      public java.lang.String getResultMsg() {
        java.lang.Object ref = resultMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string resultMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResultMsgBytes() {
        java.lang.Object ref = resultMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string resultMsg = 2;</code>
       */
      public Builder setResultMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string resultMsg = 2;</code>
       */
      public Builder clearResultMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultMsg_ = getDefaultInstance().getResultMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string resultMsg = 2;</code>
       */
      public Builder setResultMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultMsg_ = value;
        onChanged();
        return this;
      }

      private int orderStatus_ ;
      /**
       * <code>optional int32 orderStatus = 3;</code>
       */
      public boolean hasOrderStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 orderStatus = 3;</code>
       */
      public int getOrderStatus() {
        return orderStatus_;
      }
      /**
       * <code>optional int32 orderStatus = 3;</code>
       */
      public Builder setOrderStatus(int value) {
        bitField0_ |= 0x00000004;
        orderStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 orderStatus = 3;</code>
       */
      public Builder clearOrderStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        orderStatus_ = 0;
        onChanged();
        return this;
      }

      private long applyTime_ ;
      /**
       * <code>optional int64 applyTime = 4;</code>
       *
       * <pre>
       *申请归还时间
       * </pre>
       */
      public boolean hasApplyTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 applyTime = 4;</code>
       *
       * <pre>
       *申请归还时间
       * </pre>
       */
      public long getApplyTime() {
        return applyTime_;
      }
      /**
       * <code>optional int64 applyTime = 4;</code>
       *
       * <pre>
       *申请归还时间
       * </pre>
       */
      public Builder setApplyTime(long value) {
        bitField0_ |= 0x00000008;
        applyTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 applyTime = 4;</code>
       *
       * <pre>
       *申请归还时间
       * </pre>
       */
      public Builder clearApplyTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        applyTime_ = 0L;
        onChanged();
        return this;
      }

      private long revertTime_ ;
      /**
       * <code>optional int64 revertTime = 5;</code>
       *
       * <pre>
       *完成归还时间
       * </pre>
       */
      public boolean hasRevertTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 revertTime = 5;</code>
       *
       * <pre>
       *完成归还时间
       * </pre>
       */
      public long getRevertTime() {
        return revertTime_;
      }
      /**
       * <code>optional int64 revertTime = 5;</code>
       *
       * <pre>
       *完成归还时间
       * </pre>
       */
      public Builder setRevertTime(long value) {
        bitField0_ |= 0x00000010;
        revertTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 revertTime = 5;</code>
       *
       * <pre>
       *完成归还时间
       * </pre>
       */
      public Builder clearRevertTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        revertTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList evidentalImgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEvidentalImgsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          evidentalImgs_ = new com.google.protobuf.LazyStringArrayList(evidentalImgs_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string evidentalImgs = 6;</code>
       *
       * <pre>
       *归还凭证图片
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getEvidentalImgsList() {
        return evidentalImgs_.getUnmodifiableView();
      }
      /**
       * <code>repeated string evidentalImgs = 6;</code>
       *
       * <pre>
       *归还凭证图片
       * </pre>
       */
      public int getEvidentalImgsCount() {
        return evidentalImgs_.size();
      }
      /**
       * <code>repeated string evidentalImgs = 6;</code>
       *
       * <pre>
       *归还凭证图片
       * </pre>
       */
      public java.lang.String getEvidentalImgs(int index) {
        return evidentalImgs_.get(index);
      }
      /**
       * <code>repeated string evidentalImgs = 6;</code>
       *
       * <pre>
       *归还凭证图片
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEvidentalImgsBytes(int index) {
        return evidentalImgs_.getByteString(index);
      }
      /**
       * <code>repeated string evidentalImgs = 6;</code>
       *
       * <pre>
       *归还凭证图片
       * </pre>
       */
      public Builder setEvidentalImgs(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEvidentalImgsIsMutable();
        evidentalImgs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string evidentalImgs = 6;</code>
       *
       * <pre>
       *归还凭证图片
       * </pre>
       */
      public Builder addEvidentalImgs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEvidentalImgsIsMutable();
        evidentalImgs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string evidentalImgs = 6;</code>
       *
       * <pre>
       *归还凭证图片
       * </pre>
       */
      public Builder addAllEvidentalImgs(
          java.lang.Iterable<java.lang.String> values) {
        ensureEvidentalImgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, evidentalImgs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string evidentalImgs = 6;</code>
       *
       * <pre>
       *归还凭证图片
       * </pre>
       */
      public Builder clearEvidentalImgs() {
        evidentalImgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string evidentalImgs = 6;</code>
       *
       * <pre>
       *归还凭证图片
       * </pre>
       */
      public Builder addEvidentalImgsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEvidentalImgsIsMutable();
        evidentalImgs_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object revertIntro_ = "";
      /**
       * <code>optional string revertIntro = 7;</code>
       *
       * <pre>
       *归还说明
       * </pre>
       */
      public boolean hasRevertIntro() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string revertIntro = 7;</code>
       *
       * <pre>
       *归还说明
       * </pre>
       */
      public java.lang.String getRevertIntro() {
        java.lang.Object ref = revertIntro_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            revertIntro_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string revertIntro = 7;</code>
       *
       * <pre>
       *归还说明
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRevertIntroBytes() {
        java.lang.Object ref = revertIntro_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          revertIntro_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string revertIntro = 7;</code>
       *
       * <pre>
       *归还说明
       * </pre>
       */
      public Builder setRevertIntro(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        revertIntro_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string revertIntro = 7;</code>
       *
       * <pre>
       *归还说明
       * </pre>
       */
      public Builder clearRevertIntro() {
        bitField0_ = (bitField0_ & ~0x00000040);
        revertIntro_ = getDefaultInstance().getRevertIntro();
        onChanged();
        return this;
      }
      /**
       * <code>optional string revertIntro = 7;</code>
       *
       * <pre>
       *归还说明
       * </pre>
       */
      public Builder setRevertIntroBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        revertIntro_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object transportationId_ = "";
      /**
       * <code>optional string transportationId = 8;</code>
       *
       * <pre>
       *快递号
       * </pre>
       */
      public boolean hasTransportationId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string transportationId = 8;</code>
       *
       * <pre>
       *快递号
       * </pre>
       */
      public java.lang.String getTransportationId() {
        java.lang.Object ref = transportationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transportationId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string transportationId = 8;</code>
       *
       * <pre>
       *快递号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTransportationIdBytes() {
        java.lang.Object ref = transportationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transportationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string transportationId = 8;</code>
       *
       * <pre>
       *快递号
       * </pre>
       */
      public Builder setTransportationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        transportationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string transportationId = 8;</code>
       *
       * <pre>
       *快递号
       * </pre>
       */
      public Builder clearTransportationId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        transportationId_ = getDefaultInstance().getTransportationId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string transportationId = 8;</code>
       *
       * <pre>
       *快递号
       * </pre>
       */
      public Builder setTransportationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        transportationId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object transportationCompany_ = "";
      /**
       * <code>optional string transportationCompany = 9;</code>
       *
       * <pre>
       *快递公司
       * </pre>
       */
      public boolean hasTransportationCompany() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string transportationCompany = 9;</code>
       *
       * <pre>
       *快递公司
       * </pre>
       */
      public java.lang.String getTransportationCompany() {
        java.lang.Object ref = transportationCompany_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transportationCompany_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string transportationCompany = 9;</code>
       *
       * <pre>
       *快递公司
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTransportationCompanyBytes() {
        java.lang.Object ref = transportationCompany_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transportationCompany_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string transportationCompany = 9;</code>
       *
       * <pre>
       *快递公司
       * </pre>
       */
      public Builder setTransportationCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        transportationCompany_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string transportationCompany = 9;</code>
       *
       * <pre>
       *快递公司
       * </pre>
       */
      public Builder clearTransportationCompany() {
        bitField0_ = (bitField0_ & ~0x00000100);
        transportationCompany_ = getDefaultInstance().getTransportationCompany();
        onChanged();
        return this;
      }
      /**
       * <code>optional string transportationCompany = 9;</code>
       *
       * <pre>
       *快递公司
       * </pre>
       */
      public Builder setTransportationCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        transportationCompany_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object transportationIntro_ = "";
      /**
       * <code>optional string transportationIntro = 10;</code>
       *
       * <pre>
       *物流说明
       * </pre>
       */
      public boolean hasTransportationIntro() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string transportationIntro = 10;</code>
       *
       * <pre>
       *物流说明
       * </pre>
       */
      public java.lang.String getTransportationIntro() {
        java.lang.Object ref = transportationIntro_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            transportationIntro_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string transportationIntro = 10;</code>
       *
       * <pre>
       *物流说明
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTransportationIntroBytes() {
        java.lang.Object ref = transportationIntro_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transportationIntro_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string transportationIntro = 10;</code>
       *
       * <pre>
       *物流说明
       * </pre>
       */
      public Builder setTransportationIntro(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        transportationIntro_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string transportationIntro = 10;</code>
       *
       * <pre>
       *物流说明
       * </pre>
       */
      public Builder clearTransportationIntro() {
        bitField0_ = (bitField0_ & ~0x00000200);
        transportationIntro_ = getDefaultInstance().getTransportationIntro();
        onChanged();
        return this;
      }
      /**
       * <code>optional string transportationIntro = 10;</code>
       *
       * <pre>
       *物流说明
       * </pre>
       */
      public Builder setTransportationIntroBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        transportationIntro_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.qjoy.basjoo.core.model.pb.GetRevertDetailResult)
    }

    static {
      defaultInstance = new GetRevertDetailResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.qjoy.basjoo.core.model.pb.GetRevertDetailResult)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\006Revert\022\035com.qjoy.basjoo.core.model.pb\"" +
      "9\n\026GetRevertDetailRequest\022\016\n\006userId\030\001 \002(" +
      "\t\022\017\n\007orderId\030\002 \002(\t\"\374\001\n\025GetRevertDetailRe" +
      "sult\022\022\n\nresultCode\030\001 \002(\t\022\021\n\tresultMsg\030\002 " +
      "\002(\t\022\023\n\013orderStatus\030\003 \001(\005\022\021\n\tapplyTime\030\004 " +
      "\001(\003\022\022\n\nrevertTime\030\005 \001(\003\022\025\n\revidentalImgs" +
      "\030\006 \003(\t\022\023\n\013revertIntro\030\007 \001(\t\022\030\n\020transport" +
      "ationId\030\010 \001(\t\022\035\n\025transportationCompany\030\t" +
      " \001(\t\022\033\n\023transportationIntro\030\n \001(\tB\037\n\035com" +
      ".qjoy.basjoo.core.model.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailRequest_descriptor,
        new java.lang.String[] { "UserId", "OrderId", });
    internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_qjoy_basjoo_core_model_pb_GetRevertDetailResult_descriptor,
        new java.lang.String[] { "ResultCode", "ResultMsg", "OrderStatus", "ApplyTime", "RevertTime", "EvidentalImgs", "RevertIntro", "TransportationId", "TransportationCompany", "TransportationIntro", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
