// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <QJProtocolBuffers/ProtocolBuffers.h>

@class AddEvaluateReplyRequest;
@class AddEvaluateReplyResult;
@class AddEvaluateRequest;
@class AddEvaluateResult;
@class DeleteEvaluateRequest;
@class DeleteEvaluateResult;
@class ModifyEvaluateRequest;
@class ModifyEvaluateResult;

@interface AddEvaluateRequest : QJPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasOrderId;
@property (readonly) BOOL hasContent;
@property (readonly) BOOL hasLevel;
@property (nonatomic,strong) NSString* orderId;
@property (nonatomic,strong) NSString* content;
@property (nonatomic,strong) NSMutableArray * imageUrls;
@property (nonatomic)SInt32 level;
@end

@interface AddEvaluateResult : QJPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasResultCode;
@property (readonly) BOOL hasResultMsg;
@property (readonly) BOOL hasEvaluateId;
@property (nonatomic,strong) NSString* resultCode;
@property (nonatomic,strong) NSString* resultMsg;
@property (nonatomic,strong) NSString* evaluateId;
@end

@interface AddEvaluateReplyRequest : QJPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasEvaluateId;
@property (readonly) BOOL hasContent;
@property (nonatomic,strong) NSString* evaluateId;
@property (nonatomic,strong) NSString* content;
@end

@interface AddEvaluateReplyResult : QJPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasResultCode;
@property (readonly) BOOL hasResultMsg;
@property (readonly) BOOL hasReplyId;
@property (nonatomic,strong) NSString* resultCode;
@property (nonatomic,strong) NSString* resultMsg;
@property (nonatomic,strong) NSString* replyId;
@end

@interface ModifyEvaluateRequest : QJPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasEvaluateId;
@property (readonly) BOOL hasContent;
@property (readonly) BOOL hasLevel;
@property (nonatomic,strong) NSString* evaluateId;
@property (nonatomic,strong) NSString* content;
@property (nonatomic,strong) NSMutableArray * imageUrls;
@property (nonatomic)SInt32 level;
@end

@interface ModifyEvaluateResult : QJPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasResultCode;
@property (readonly) BOOL hasResultMsg;
@property (nonatomic,strong) NSString* resultCode;
@property (nonatomic,strong) NSString* resultMsg;
@end

@interface DeleteEvaluateRequest : QJPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasEvaluateId;
@property (nonatomic,strong) NSString* evaluateId;
@end

@interface DeleteEvaluateResult : QJPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasResultCode;
@property (readonly) BOOL hasResultMsg;
@property (nonatomic,strong) NSString* resultCode;
@property (nonatomic,strong) NSString* resultMsg;
@end

