// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Product.pb.h"

@implementation SearchProductListRequest

- (instancetype) init {
  if ((self = [super init])) {
    _keywords = @"";
    _searchType = @"";
    _orderBy = 0;
    _startIndex = 0;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasKeywords) {
    [output writeString:1 value:self.keywords];
  }
  if (self.hasSearchType) {
    [output writeString:2 value:self.searchType];
  }
  if (self.hasOrderBy) {
    [output writeInt32:3 value:self.orderBy];
  }
  if (self.hasStartIndex) {
    [output writeInt32:4 value:self.startIndex];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasKeywords) {
    size_ += computeStringSize(1, self.keywords);
  }
  if (self.hasSearchType) {
    size_ += computeStringSize(2, self.searchType);
  }
  if (self.hasOrderBy) {
    size_ += computeInt32Size(3, self.orderBy);
  }
  if (self.hasStartIndex) {
    size_ += computeInt32Size(4, self.startIndex);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (SearchProductListRequest*) parseFromData:(NSData*) data {
  SearchProductListRequest* result = [[SearchProductListRequest alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasKeywords) {
    [output appendFormat:@"%@%@: %@\n", indent, @"keywords", self.keywords];
  }
  if (self.hasSearchType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"searchType", self.searchType];
  }
  if (self.hasOrderBy) {
    [output appendFormat:@"%@%@: %@\n", indent, @"orderBy", [NSNumber numberWithInteger:self.orderBy]];
  }
  if (self.hasStartIndex) {
    [output appendFormat:@"%@%@: %@\n", indent, @"startIndex", [NSNumber numberWithInteger:self.startIndex]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setKeywords:(NSString*) value {
  _hasKeywords = YES;
  _keywords = value;
}
- (void) setSearchType:(NSString*) value {
  _hasSearchType = YES;
  _searchType = value;
}
- (void) setOrderBy:(SInt32) value {
  _hasOrderBy = YES;
  _orderBy = value;
}
- (void) setStartIndex:(SInt32) value {
  _hasStartIndex = YES;
  _startIndex = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setKeywords:[input readString]];
        break;
      }
      case 18: {
        [self setSearchType:[input readString]];
        break;
      }
      case 24: {
        [self setOrderBy:[input readInt32]];
        break;
      }
      case 32: {
        [self setStartIndex:[input readInt32]];
        break;
      }
    }
  }
}
@end


@implementation SearchProductListResult

- (instancetype) init {
  if ((self = [super init])) {
    _resultCode = @"";
    _resultMsg = @"";
    _maxIndex = 0;
    _hasMore = NO;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasResultCode) {
    [output writeString:1 value:self.resultCode];
  }
  if (self.hasResultMsg) {
    [output writeString:2 value:self.resultMsg];
  }
  if (self.hasMaxIndex) {
    [output writeInt32:3 value:self.maxIndex];
  }
  if (self.hasHasMore) {
    [output writeBool:4 value:self.hasMore];
  }
  [self.productLiteInfo enumerateObjectsUsingBlock:^(ProductLiteInfo *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:5 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasResultCode) {
    size_ += computeStringSize(1, self.resultCode);
  }
  if (self.hasResultMsg) {
    size_ += computeStringSize(2, self.resultMsg);
  }
  if (self.hasMaxIndex) {
    size_ += computeInt32Size(3, self.maxIndex);
  }
  if (self.hasHasMore) {
    size_ += computeBoolSize(4, self.hasMore);
  }
  [self.productLiteInfo enumerateObjectsUsingBlock:^(ProductLiteInfo *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(5, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (SearchProductListResult*) parseFromData:(NSData*) data {
  SearchProductListResult* result = [[SearchProductListResult alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasResultCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultCode", self.resultCode];
  }
  if (self.hasResultMsg) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultMsg", self.resultMsg];
  }
  if (self.hasMaxIndex) {
    [output appendFormat:@"%@%@: %@\n", indent, @"maxIndex", [NSNumber numberWithInteger:self.maxIndex]];
  }
  if (self.hasHasMore) {
    [output appendFormat:@"%@%@: %@\n", indent, @"hasMore", [NSNumber numberWithBool:self.hasMore]];
  }
  [self.productLiteInfo enumerateObjectsUsingBlock:^(ProductLiteInfo *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"productLiteInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setResultCode:(NSString*) value {
  _hasResultCode = YES;
  _resultCode = value;
}
- (void) setResultMsg:(NSString*) value {
  _hasResultMsg = YES;
  _resultMsg = value;
}
- (void) setMaxIndex:(SInt32) value {
  _hasMaxIndex = YES;
  _maxIndex = value;
}
- (void) setHasMore:(BOOL) value {
  _hasHasMore = YES;
  _hasMore = value;
}
- (void)setProductLiteInfoArray:(NSArray *)array {
  _productLiteInfo = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addProductLiteInfo:(ProductLiteInfo*)value {
  if (_productLiteInfo == nil) {
    _productLiteInfo = [[NSMutableArray alloc]init];
  }
  [_productLiteInfo addObject:value];
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setResultCode:[input readString]];
        break;
      }
      case 18: {
        [self setResultMsg:[input readString]];
        break;
      }
      case 24: {
        [self setMaxIndex:[input readInt32]];
        break;
      }
      case 32: {
        [self setHasMore:[input readBool]];
        break;
      }
      case 42: {
        ProductLiteInfo* sub = [[ProductLiteInfo alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addProductLiteInfo:sub];
        break;
      }
    }
  }
}
@end


@implementation ProductLiteInfo

- (instancetype) init {
  if ((self = [super init])) {
    _productId = @"";
    _productType = @"";
    _brand = @"";
    _mainImageUrl = @"";
    _desc = @"";
    _lowestRent = 0;
    _unit = 0;
    _rentCount = 0L;
    _marketPrice = 0;
    _pledgePrice = 0;
    _favorited = NO;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasProductId) {
    [output writeString:1 value:self.productId];
  }
  if (self.hasProductType) {
    [output writeString:2 value:self.productType];
  }
  if (self.hasBrand) {
    [output writeString:3 value:self.brand];
  }
  if (self.hasMainImageUrl) {
    [output writeString:4 value:self.mainImageUrl];
  }
  if (self.hasDesc) {
    [output writeString:5 value:self.desc];
  }
  if (self.hasLowestRent) {
    [output writeDouble:6 value:self.lowestRent];
  }
  if (self.hasUnit) {
    [output writeInt32:7 value:self.unit];
  }
  if (self.hasRentCount) {
    [output writeInt64:8 value:self.rentCount];
  }
  if (self.hasMarketPrice) {
    [output writeDouble:9 value:self.marketPrice];
  }
  if (self.hasPledgePrice) {
    [output writeDouble:10 value:self.pledgePrice];
  }
  if (self.hasFavorited) {
    [output writeBool:11 value:self.favorited];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasProductId) {
    size_ += computeStringSize(1, self.productId);
  }
  if (self.hasProductType) {
    size_ += computeStringSize(2, self.productType);
  }
  if (self.hasBrand) {
    size_ += computeStringSize(3, self.brand);
  }
  if (self.hasMainImageUrl) {
    size_ += computeStringSize(4, self.mainImageUrl);
  }
  if (self.hasDesc) {
    size_ += computeStringSize(5, self.desc);
  }
  if (self.hasLowestRent) {
    size_ += computeDoubleSize(6, self.lowestRent);
  }
  if (self.hasUnit) {
    size_ += computeInt32Size(7, self.unit);
  }
  if (self.hasRentCount) {
    size_ += computeInt64Size(8, self.rentCount);
  }
  if (self.hasMarketPrice) {
    size_ += computeDoubleSize(9, self.marketPrice);
  }
  if (self.hasPledgePrice) {
    size_ += computeDoubleSize(10, self.pledgePrice);
  }
  if (self.hasFavorited) {
    size_ += computeBoolSize(11, self.favorited);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ProductLiteInfo*) parseFromData:(NSData*) data {
  ProductLiteInfo* result = [[ProductLiteInfo alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasProductId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productId", self.productId];
  }
  if (self.hasProductType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productType", self.productType];
  }
  if (self.hasBrand) {
    [output appendFormat:@"%@%@: %@\n", indent, @"brand", self.brand];
  }
  if (self.hasMainImageUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"mainImageUrl", self.mainImageUrl];
  }
  if (self.hasDesc) {
    [output appendFormat:@"%@%@: %@\n", indent, @"desc", self.desc];
  }
  if (self.hasLowestRent) {
    [output appendFormat:@"%@%@: %@\n", indent, @"lowestRent", [NSNumber numberWithDouble:self.lowestRent]];
  }
  if (self.hasUnit) {
    [output appendFormat:@"%@%@: %@\n", indent, @"unit", [NSNumber numberWithInteger:self.unit]];
  }
  if (self.hasRentCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentCount", [NSNumber numberWithLongLong:self.rentCount]];
  }
  if (self.hasMarketPrice) {
    [output appendFormat:@"%@%@: %@\n", indent, @"marketPrice", [NSNumber numberWithDouble:self.marketPrice]];
  }
  if (self.hasPledgePrice) {
    [output appendFormat:@"%@%@: %@\n", indent, @"pledgePrice", [NSNumber numberWithDouble:self.pledgePrice]];
  }
  if (self.hasFavorited) {
    [output appendFormat:@"%@%@: %@\n", indent, @"favorited", [NSNumber numberWithBool:self.favorited]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setProductId:(NSString*) value {
  _hasProductId = YES;
  _productId = value;
}
- (void) setProductType:(NSString*) value {
  _hasProductType = YES;
  _productType = value;
}
- (void) setBrand:(NSString*) value {
  _hasBrand = YES;
  _brand = value;
}
- (void) setMainImageUrl:(NSString*) value {
  _hasMainImageUrl = YES;
  _mainImageUrl = value;
}
- (void) setDesc:(NSString*) value {
  _hasDesc = YES;
  _desc = value;
}
- (void) setLowestRent:(Float64) value {
  _hasLowestRent = YES;
  _lowestRent = value;
}
- (void) setUnit:(SInt32) value {
  _hasUnit = YES;
  _unit = value;
}
- (void) setRentCount:(SInt64) value {
  _hasRentCount = YES;
  _rentCount = value;
}
- (void) setMarketPrice:(Float64) value {
  _hasMarketPrice = YES;
  _marketPrice = value;
}
- (void) setPledgePrice:(Float64) value {
  _hasPledgePrice = YES;
  _pledgePrice = value;
}
- (void) setFavorited:(BOOL) value {
  _hasFavorited = YES;
  _favorited = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setProductId:[input readString]];
        break;
      }
      case 18: {
        [self setProductType:[input readString]];
        break;
      }
      case 26: {
        [self setBrand:[input readString]];
        break;
      }
      case 34: {
        [self setMainImageUrl:[input readString]];
        break;
      }
      case 42: {
        [self setDesc:[input readString]];
        break;
      }
      case 49: {
        [self setLowestRent:[input readDouble]];
        break;
      }
      case 56: {
        [self setUnit:[input readInt32]];
        break;
      }
      case 64: {
        [self setRentCount:[input readInt64]];
        break;
      }
      case 73: {
        [self setMarketPrice:[input readDouble]];
        break;
      }
      case 81: {
        [self setPledgePrice:[input readDouble]];
        break;
      }
      case 88: {
        [self setFavorited:[input readBool]];
        break;
      }
    }
  }
}
@end


@implementation ProductDetailRequest

- (instancetype) init {
  if ((self = [super init])) {
    _productId = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasProductId) {
    [output writeString:1 value:self.productId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasProductId) {
    size_ += computeStringSize(1, self.productId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ProductDetailRequest*) parseFromData:(NSData*) data {
  ProductDetailRequest* result = [[ProductDetailRequest alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasProductId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productId", self.productId];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setProductId:(NSString*) value {
  _hasProductId = YES;
  _productId = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setProductId:[input readString]];
        break;
      }
    }
  }
}
@end


@implementation ProductDetailResult

- (instancetype) init {
  if ((self = [super init])) {
    _resultCode = @"";
    _resultMsg = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasResultCode) {
    [output writeString:1 value:self.resultCode];
  }
  if (self.hasResultMsg) {
    [output writeString:2 value:self.resultMsg];
  }
  if (self.hasProductDetailInfo) {
    [output writeMessage:3 value:self.productDetailInfo];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasResultCode) {
    size_ += computeStringSize(1, self.resultCode);
  }
  if (self.hasResultMsg) {
    size_ += computeStringSize(2, self.resultMsg);
  }
  if (self.hasProductDetailInfo) {
    size_ += computeMessageSize(3, self.productDetailInfo);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ProductDetailResult*) parseFromData:(NSData*) data {
  ProductDetailResult* result = [[ProductDetailResult alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasResultCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultCode", self.resultCode];
  }
  if (self.hasResultMsg) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultMsg", self.resultMsg];
  }
  if (self.hasProductDetailInfo) {
    [output appendFormat:@"%@%@ {\n", indent, @"productDetailInfo"];
    [self.productDetailInfo writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setResultCode:(NSString*) value {
  _hasResultCode = YES;
  _resultCode = value;
}
- (void) setResultMsg:(NSString*) value {
  _hasResultMsg = YES;
  _resultMsg = value;
}
- (void) setProductDetailInfo:(ProductDetailInfo*) value {
  _hasProductDetailInfo = YES;
  _productDetailInfo = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setResultCode:[input readString]];
        break;
      }
      case 18: {
        [self setResultMsg:[input readString]];
        break;
      }
      case 26: {
        ProductDetailInfo* sub = [[ProductDetailInfo alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self setProductDetailInfo:sub];
        break;
      }
    }
  }
}
@end


@implementation ProductDetailInfo

- (instancetype) init {
  if ((self = [super init])) {
    _productId = @"";
    _productType = @"";
    _brand = @"";
    _desc = @"";
    _ageBracket = @"";
    _lowestRent = 0;
    _unit = 0;
    _rentCount = 0L;
    _maxAvailable = 0L;
    _marketPrice = 0;
    _pledgePrice = 0;
    _transportationPrice = 0;
    _location = @"";
    _evaluateCount = 0L;
    _favorited = NO;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasProductId) {
    [output writeString:1 value:self.productId];
  }
  if (self.hasProductType) {
    [output writeString:2 value:self.productType];
  }
  if (self.hasBrand) {
    [output writeString:3 value:self.brand];
  }
  [self.imageUrl enumerateObjectsUsingBlock:^(NSString *element, NSUInteger idx, BOOL *stop) {
    [output writeString:4 value:element];
  }];
  if (self.hasDesc) {
    [output writeString:5 value:self.desc];
  }
  if (self.hasAgeBracket) {
    [output writeString:6 value:self.ageBracket];
  }
  if (self.hasLowestRent) {
    [output writeDouble:7 value:self.lowestRent];
  }
  if (self.hasUnit) {
    [output writeInt32:8 value:self.unit];
  }
  if (self.hasRentCount) {
    [output writeInt64:9 value:self.rentCount];
  }
  if (self.hasMaxAvailable) {
    [output writeInt64:10 value:self.maxAvailable];
  }
  if (self.hasMarketPrice) {
    [output writeDouble:11 value:self.marketPrice];
  }
  if (self.hasPledgePrice) {
    [output writeDouble:12 value:self.pledgePrice];
  }
  if (self.hasTransportationPrice) {
    [output writeDouble:13 value:self.transportationPrice];
  }
  if (self.hasLocation) {
    [output writeString:14 value:self.location];
  }
  [self.categoryInfo enumerateObjectsUsingBlock:^(CategoryInfo *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:15 value:element];
  }];
  [self.shortRentInfo enumerateObjectsUsingBlock:^(ShortRentInfo *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:16 value:element];
  }];
  [self.longRentInfo enumerateObjectsUsingBlock:^(LongRentInfo *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:17 value:element];
  }];
  [self.baseParam enumerateObjectsUsingBlock:^(ProductBaseParam *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:18 value:element];
  }];
  [self.imageParamUrls enumerateObjectsUsingBlock:^(NSString *element, NSUInteger idx, BOOL *stop) {
    [output writeString:19 value:element];
  }];
  if (self.hasEvaluateCount) {
    [output writeInt64:20 value:self.evaluateCount];
  }
  [self.productEvaluateInfo enumerateObjectsUsingBlock:^(ProductEvaluateInfo *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:21 value:element];
  }];
  if (self.hasFavorited) {
    [output writeBool:22 value:self.favorited];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasProductId) {
    size_ += computeStringSize(1, self.productId);
  }
  if (self.hasProductType) {
    size_ += computeStringSize(2, self.productType);
  }
  if (self.hasBrand) {
    size_ += computeStringSize(3, self.brand);
  }
  {
    __block SInt32 dataSize = 0;
    const NSUInteger count = self.imageUrl.count;
    [self.imageUrl enumerateObjectsUsingBlock:^(NSString *element, NSUInteger idx, BOOL *stop) {
      dataSize += computeStringSizeNoTag(element);
    }];
    size_ += dataSize;
    size_ += (SInt32)(1 * count);
  }
  if (self.hasDesc) {
    size_ += computeStringSize(5, self.desc);
  }
  if (self.hasAgeBracket) {
    size_ += computeStringSize(6, self.ageBracket);
  }
  if (self.hasLowestRent) {
    size_ += computeDoubleSize(7, self.lowestRent);
  }
  if (self.hasUnit) {
    size_ += computeInt32Size(8, self.unit);
  }
  if (self.hasRentCount) {
    size_ += computeInt64Size(9, self.rentCount);
  }
  if (self.hasMaxAvailable) {
    size_ += computeInt64Size(10, self.maxAvailable);
  }
  if (self.hasMarketPrice) {
    size_ += computeDoubleSize(11, self.marketPrice);
  }
  if (self.hasPledgePrice) {
    size_ += computeDoubleSize(12, self.pledgePrice);
  }
  if (self.hasTransportationPrice) {
    size_ += computeDoubleSize(13, self.transportationPrice);
  }
  if (self.hasLocation) {
    size_ += computeStringSize(14, self.location);
  }
  [self.categoryInfo enumerateObjectsUsingBlock:^(CategoryInfo *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(15, element);
  }];
  [self.shortRentInfo enumerateObjectsUsingBlock:^(ShortRentInfo *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(16, element);
  }];
  [self.longRentInfo enumerateObjectsUsingBlock:^(LongRentInfo *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(17, element);
  }];
  [self.baseParam enumerateObjectsUsingBlock:^(ProductBaseParam *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(18, element);
  }];
  {
    __block SInt32 dataSize = 0;
    const NSUInteger count = self.imageParamUrls.count;
    [self.imageParamUrls enumerateObjectsUsingBlock:^(NSString *element, NSUInteger idx, BOOL *stop) {
      dataSize += computeStringSizeNoTag(element);
    }];
    size_ += dataSize;
    size_ += (SInt32)(2 * count);
  }
  if (self.hasEvaluateCount) {
    size_ += computeInt64Size(20, self.evaluateCount);
  }
  [self.productEvaluateInfo enumerateObjectsUsingBlock:^(ProductEvaluateInfo *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(21, element);
  }];
  if (self.hasFavorited) {
    size_ += computeBoolSize(22, self.favorited);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ProductDetailInfo*) parseFromData:(NSData*) data {
  ProductDetailInfo* result = [[ProductDetailInfo alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasProductId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productId", self.productId];
  }
  if (self.hasProductType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productType", self.productType];
  }
  if (self.hasBrand) {
    [output appendFormat:@"%@%@: %@\n", indent, @"brand", self.brand];
  }
  [self.imageUrl enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@: %@\n", indent, @"imageUrl", obj];
  }];
  if (self.hasDesc) {
    [output appendFormat:@"%@%@: %@\n", indent, @"desc", self.desc];
  }
  if (self.hasAgeBracket) {
    [output appendFormat:@"%@%@: %@\n", indent, @"ageBracket", self.ageBracket];
  }
  if (self.hasLowestRent) {
    [output appendFormat:@"%@%@: %@\n", indent, @"lowestRent", [NSNumber numberWithDouble:self.lowestRent]];
  }
  if (self.hasUnit) {
    [output appendFormat:@"%@%@: %@\n", indent, @"unit", [NSNumber numberWithInteger:self.unit]];
  }
  if (self.hasRentCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentCount", [NSNumber numberWithLongLong:self.rentCount]];
  }
  if (self.hasMaxAvailable) {
    [output appendFormat:@"%@%@: %@\n", indent, @"maxAvailable", [NSNumber numberWithLongLong:self.maxAvailable]];
  }
  if (self.hasMarketPrice) {
    [output appendFormat:@"%@%@: %@\n", indent, @"marketPrice", [NSNumber numberWithDouble:self.marketPrice]];
  }
  if (self.hasPledgePrice) {
    [output appendFormat:@"%@%@: %@\n", indent, @"pledgePrice", [NSNumber numberWithDouble:self.pledgePrice]];
  }
  if (self.hasTransportationPrice) {
    [output appendFormat:@"%@%@: %@\n", indent, @"transportationPrice", [NSNumber numberWithDouble:self.transportationPrice]];
  }
  if (self.hasLocation) {
    [output appendFormat:@"%@%@: %@\n", indent, @"location", self.location];
  }
  [self.categoryInfo enumerateObjectsUsingBlock:^(CategoryInfo *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"categoryInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.shortRentInfo enumerateObjectsUsingBlock:^(ShortRentInfo *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"shortRentInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.longRentInfo enumerateObjectsUsingBlock:^(LongRentInfo *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"longRentInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.baseParam enumerateObjectsUsingBlock:^(ProductBaseParam *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"baseParam"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.imageParamUrls enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@: %@\n", indent, @"imageParamUrls", obj];
  }];
  if (self.hasEvaluateCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"evaluateCount", [NSNumber numberWithLongLong:self.evaluateCount]];
  }
  [self.productEvaluateInfo enumerateObjectsUsingBlock:^(ProductEvaluateInfo *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"productEvaluateInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  if (self.hasFavorited) {
    [output appendFormat:@"%@%@: %@\n", indent, @"favorited", [NSNumber numberWithBool:self.favorited]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setProductId:(NSString*) value {
  _hasProductId = YES;
  _productId = value;
}
- (void) setProductType:(NSString*) value {
  _hasProductType = YES;
  _productType = value;
}
- (void) setBrand:(NSString*) value {
  _hasBrand = YES;
  _brand = value;
}
- (void)setImageUrlArray:(NSArray *)array {
  _imageUrl = [[NSMutableArray alloc] initWithArray:array];
}
- (void)addImageUrl:(NSString*)value {
  if (_imageUrl == nil) {
    _imageUrl = [[NSMutableArray alloc]init];
  }
  [_imageUrl addObject:value];
}
- (void) setDesc:(NSString*) value {
  _hasDesc = YES;
  _desc = value;
}
- (void) setAgeBracket:(NSString*) value {
  _hasAgeBracket = YES;
  _ageBracket = value;
}
- (void) setLowestRent:(Float64) value {
  _hasLowestRent = YES;
  _lowestRent = value;
}
- (void) setUnit:(SInt32) value {
  _hasUnit = YES;
  _unit = value;
}
- (void) setRentCount:(SInt64) value {
  _hasRentCount = YES;
  _rentCount = value;
}
- (void) setMaxAvailable:(SInt64) value {
  _hasMaxAvailable = YES;
  _maxAvailable = value;
}
- (void) setMarketPrice:(Float64) value {
  _hasMarketPrice = YES;
  _marketPrice = value;
}
- (void) setPledgePrice:(Float64) value {
  _hasPledgePrice = YES;
  _pledgePrice = value;
}
- (void) setTransportationPrice:(Float64) value {
  _hasTransportationPrice = YES;
  _transportationPrice = value;
}
- (void) setLocation:(NSString*) value {
  _hasLocation = YES;
  _location = value;
}
- (void)setCategoryInfoArray:(NSArray *)array {
  _categoryInfo = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addCategoryInfo:(CategoryInfo*)value {
  if (_categoryInfo == nil) {
    _categoryInfo = [[NSMutableArray alloc]init];
  }
  [_categoryInfo addObject:value];
}
- (void)setShortRentInfoArray:(NSArray *)array {
  _shortRentInfo = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addShortRentInfo:(ShortRentInfo*)value {
  if (_shortRentInfo == nil) {
    _shortRentInfo = [[NSMutableArray alloc]init];
  }
  [_shortRentInfo addObject:value];
}
- (void)setLongRentInfoArray:(NSArray *)array {
  _longRentInfo = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addLongRentInfo:(LongRentInfo*)value {
  if (_longRentInfo == nil) {
    _longRentInfo = [[NSMutableArray alloc]init];
  }
  [_longRentInfo addObject:value];
}
- (void)setBaseParamArray:(NSArray *)array {
  _baseParam = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addBaseParam:(ProductBaseParam*)value {
  if (_baseParam == nil) {
    _baseParam = [[NSMutableArray alloc]init];
  }
  [_baseParam addObject:value];
}
- (void)setImageParamUrlsArray:(NSArray *)array {
  _imageParamUrls = [[NSMutableArray alloc] initWithArray:array];
}
- (void)addImageParamUrls:(NSString*)value {
  if (_imageParamUrls == nil) {
    _imageParamUrls = [[NSMutableArray alloc]init];
  }
  [_imageParamUrls addObject:value];
}
- (void) setEvaluateCount:(SInt64) value {
  _hasEvaluateCount = YES;
  _evaluateCount = value;
}
- (void)setProductEvaluateInfoArray:(NSArray *)array {
  _productEvaluateInfo = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addProductEvaluateInfo:(ProductEvaluateInfo*)value {
  if (_productEvaluateInfo == nil) {
    _productEvaluateInfo = [[NSMutableArray alloc]init];
  }
  [_productEvaluateInfo addObject:value];
}
- (void) setFavorited:(BOOL) value {
  _hasFavorited = YES;
  _favorited = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setProductId:[input readString]];
        break;
      }
      case 18: {
        [self setProductType:[input readString]];
        break;
      }
      case 26: {
        [self setBrand:[input readString]];
        break;
      }
      case 34: {
        [self addImageUrl:[input readString]];
        break;
      }
      case 42: {
        [self setDesc:[input readString]];
        break;
      }
      case 50: {
        [self setAgeBracket:[input readString]];
        break;
      }
      case 57: {
        [self setLowestRent:[input readDouble]];
        break;
      }
      case 64: {
        [self setUnit:[input readInt32]];
        break;
      }
      case 72: {
        [self setRentCount:[input readInt64]];
        break;
      }
      case 80: {
        [self setMaxAvailable:[input readInt64]];
        break;
      }
      case 89: {
        [self setMarketPrice:[input readDouble]];
        break;
      }
      case 97: {
        [self setPledgePrice:[input readDouble]];
        break;
      }
      case 105: {
        [self setTransportationPrice:[input readDouble]];
        break;
      }
      case 114: {
        [self setLocation:[input readString]];
        break;
      }
      case 122: {
        CategoryInfo* sub = [[CategoryInfo alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addCategoryInfo:sub];
        break;
      }
      case 130: {
        ShortRentInfo* sub = [[ShortRentInfo alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addShortRentInfo:sub];
        break;
      }
      case 138: {
        LongRentInfo* sub = [[LongRentInfo alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addLongRentInfo:sub];
        break;
      }
      case 146: {
        ProductBaseParam* sub = [[ProductBaseParam alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addBaseParam:sub];
        break;
      }
      case 154: {
        [self addImageParamUrls:[input readString]];
        break;
      }
      case 160: {
        [self setEvaluateCount:[input readInt64]];
        break;
      }
      case 170: {
        ProductEvaluateInfo* sub = [[ProductEvaluateInfo alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addProductEvaluateInfo:sub];
        break;
      }
      case 176: {
        [self setFavorited:[input readBool]];
        break;
      }
    }
  }
}
@end


@implementation CategoryInfo

- (instancetype) init {
  if ((self = [super init])) {
    _categoryCode = @"";
    _categoryName = @"";
    _stockCount = 0L;
    _categoryImgUrl = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasCategoryCode) {
    [output writeString:1 value:self.categoryCode];
  }
  if (self.hasCategoryName) {
    [output writeString:2 value:self.categoryName];
  }
  if (self.hasStockCount) {
    [output writeInt64:3 value:self.stockCount];
  }
  if (self.hasCategoryImgUrl) {
    [output writeString:4 value:self.categoryImgUrl];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasCategoryCode) {
    size_ += computeStringSize(1, self.categoryCode);
  }
  if (self.hasCategoryName) {
    size_ += computeStringSize(2, self.categoryName);
  }
  if (self.hasStockCount) {
    size_ += computeInt64Size(3, self.stockCount);
  }
  if (self.hasCategoryImgUrl) {
    size_ += computeStringSize(4, self.categoryImgUrl);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (CategoryInfo*) parseFromData:(NSData*) data {
  CategoryInfo* result = [[CategoryInfo alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasCategoryCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"categoryCode", self.categoryCode];
  }
  if (self.hasCategoryName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"categoryName", self.categoryName];
  }
  if (self.hasStockCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"stockCount", [NSNumber numberWithLongLong:self.stockCount]];
  }
  if (self.hasCategoryImgUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"categoryImgUrl", self.categoryImgUrl];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setCategoryCode:(NSString*) value {
  _hasCategoryCode = YES;
  _categoryCode = value;
}
- (void) setCategoryName:(NSString*) value {
  _hasCategoryName = YES;
  _categoryName = value;
}
- (void) setStockCount:(SInt64) value {
  _hasStockCount = YES;
  _stockCount = value;
}
- (void) setCategoryImgUrl:(NSString*) value {
  _hasCategoryImgUrl = YES;
  _categoryImgUrl = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setCategoryCode:[input readString]];
        break;
      }
      case 18: {
        [self setCategoryName:[input readString]];
        break;
      }
      case 24: {
        [self setStockCount:[input readInt64]];
        break;
      }
      case 34: {
        [self setCategoryImgUrl:[input readString]];
        break;
      }
    }
  }
}
@end


@implementation ShortRentInfo

- (instancetype) init {
  if ((self = [super init])) {
    _rentCode = @"";
    _rentPeriod = @"";
    _rentPricePerDay = 0;
    _totalPrice = 0;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasRentCode) {
    [output writeString:1 value:self.rentCode];
  }
  if (self.hasRentPeriod) {
    [output writeString:2 value:self.rentPeriod];
  }
  if (self.hasRentPricePerDay) {
    [output writeDouble:3 value:self.rentPricePerDay];
  }
  if (self.hasTotalPrice) {
    [output writeDouble:4 value:self.totalPrice];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasRentCode) {
    size_ += computeStringSize(1, self.rentCode);
  }
  if (self.hasRentPeriod) {
    size_ += computeStringSize(2, self.rentPeriod);
  }
  if (self.hasRentPricePerDay) {
    size_ += computeDoubleSize(3, self.rentPricePerDay);
  }
  if (self.hasTotalPrice) {
    size_ += computeDoubleSize(4, self.totalPrice);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ShortRentInfo*) parseFromData:(NSData*) data {
  ShortRentInfo* result = [[ShortRentInfo alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasRentCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentCode", self.rentCode];
  }
  if (self.hasRentPeriod) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentPeriod", self.rentPeriod];
  }
  if (self.hasRentPricePerDay) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentPricePerDay", [NSNumber numberWithDouble:self.rentPricePerDay]];
  }
  if (self.hasTotalPrice) {
    [output appendFormat:@"%@%@: %@\n", indent, @"totalPrice", [NSNumber numberWithDouble:self.totalPrice]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setRentCode:(NSString*) value {
  _hasRentCode = YES;
  _rentCode = value;
}
- (void) setRentPeriod:(NSString*) value {
  _hasRentPeriod = YES;
  _rentPeriod = value;
}
- (void) setRentPricePerDay:(Float64) value {
  _hasRentPricePerDay = YES;
  _rentPricePerDay = value;
}
- (void) setTotalPrice:(Float64) value {
  _hasTotalPrice = YES;
  _totalPrice = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setRentCode:[input readString]];
        break;
      }
      case 18: {
        [self setRentPeriod:[input readString]];
        break;
      }
      case 25: {
        [self setRentPricePerDay:[input readDouble]];
        break;
      }
      case 33: {
        [self setTotalPrice:[input readDouble]];
        break;
      }
    }
  }
}
@end


@implementation LongRentInfo

- (instancetype) init {
  if ((self = [super init])) {
    _rentCode = @"";
    _rentPeriod = @"";
    _rentPeriodName = @"";
    _rentPricePerDay = 0;
    _rentPricePerMonth = 0;
    _totalPrice = 0;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasRentCode) {
    [output writeString:1 value:self.rentCode];
  }
  if (self.hasRentPeriod) {
    [output writeString:2 value:self.rentPeriod];
  }
  if (self.hasRentPeriodName) {
    [output writeString:3 value:self.rentPeriodName];
  }
  if (self.hasRentPricePerDay) {
    [output writeDouble:4 value:self.rentPricePerDay];
  }
  if (self.hasRentPricePerMonth) {
    [output writeDouble:5 value:self.rentPricePerMonth];
  }
  if (self.hasTotalPrice) {
    [output writeDouble:6 value:self.totalPrice];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasRentCode) {
    size_ += computeStringSize(1, self.rentCode);
  }
  if (self.hasRentPeriod) {
    size_ += computeStringSize(2, self.rentPeriod);
  }
  if (self.hasRentPeriodName) {
    size_ += computeStringSize(3, self.rentPeriodName);
  }
  if (self.hasRentPricePerDay) {
    size_ += computeDoubleSize(4, self.rentPricePerDay);
  }
  if (self.hasRentPricePerMonth) {
    size_ += computeDoubleSize(5, self.rentPricePerMonth);
  }
  if (self.hasTotalPrice) {
    size_ += computeDoubleSize(6, self.totalPrice);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (LongRentInfo*) parseFromData:(NSData*) data {
  LongRentInfo* result = [[LongRentInfo alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasRentCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentCode", self.rentCode];
  }
  if (self.hasRentPeriod) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentPeriod", self.rentPeriod];
  }
  if (self.hasRentPeriodName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentPeriodName", self.rentPeriodName];
  }
  if (self.hasRentPricePerDay) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentPricePerDay", [NSNumber numberWithDouble:self.rentPricePerDay]];
  }
  if (self.hasRentPricePerMonth) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentPricePerMonth", [NSNumber numberWithDouble:self.rentPricePerMonth]];
  }
  if (self.hasTotalPrice) {
    [output appendFormat:@"%@%@: %@\n", indent, @"totalPrice", [NSNumber numberWithDouble:self.totalPrice]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setRentCode:(NSString*) value {
  _hasRentCode = YES;
  _rentCode = value;
}
- (void) setRentPeriod:(NSString*) value {
  _hasRentPeriod = YES;
  _rentPeriod = value;
}
- (void) setRentPeriodName:(NSString*) value {
  _hasRentPeriodName = YES;
  _rentPeriodName = value;
}
- (void) setRentPricePerDay:(Float64) value {
  _hasRentPricePerDay = YES;
  _rentPricePerDay = value;
}
- (void) setRentPricePerMonth:(Float64) value {
  _hasRentPricePerMonth = YES;
  _rentPricePerMonth = value;
}
- (void) setTotalPrice:(Float64) value {
  _hasTotalPrice = YES;
  _totalPrice = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setRentCode:[input readString]];
        break;
      }
      case 18: {
        [self setRentPeriod:[input readString]];
        break;
      }
      case 26: {
        [self setRentPeriodName:[input readString]];
        break;
      }
      case 33: {
        [self setRentPricePerDay:[input readDouble]];
        break;
      }
      case 41: {
        [self setRentPricePerMonth:[input readDouble]];
        break;
      }
      case 49: {
        [self setTotalPrice:[input readDouble]];
        break;
      }
    }
  }
}
@end


@implementation ProductBaseParam

- (instancetype) init {
  if ((self = [super init])) {
    _code = @"";
    _showKey = @"";
    _showValue = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasCode) {
    [output writeString:1 value:self.code];
  }
  if (self.hasShowKey) {
    [output writeString:2 value:self.showKey];
  }
  if (self.hasShowValue) {
    [output writeString:3 value:self.showValue];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasCode) {
    size_ += computeStringSize(1, self.code);
  }
  if (self.hasShowKey) {
    size_ += computeStringSize(2, self.showKey);
  }
  if (self.hasShowValue) {
    size_ += computeStringSize(3, self.showValue);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ProductBaseParam*) parseFromData:(NSData*) data {
  ProductBaseParam* result = [[ProductBaseParam alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"code", self.code];
  }
  if (self.hasShowKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"showKey", self.showKey];
  }
  if (self.hasShowValue) {
    [output appendFormat:@"%@%@: %@\n", indent, @"showValue", self.showValue];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setCode:(NSString*) value {
  _hasCode = YES;
  _code = value;
}
- (void) setShowKey:(NSString*) value {
  _hasShowKey = YES;
  _showKey = value;
}
- (void) setShowValue:(NSString*) value {
  _hasShowValue = YES;
  _showValue = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setCode:[input readString]];
        break;
      }
      case 18: {
        [self setShowKey:[input readString]];
        break;
      }
      case 26: {
        [self setShowValue:[input readString]];
        break;
      }
    }
  }
}
@end


@implementation ProductEvaluateInfo

- (instancetype) init {
  if ((self = [super init])) {
    _time = 0L;
    _userId = @"";
    _userName = @"";
    _headIconUrl = @"";
    _userLevel = 0;
    _rentCategoryName = @"";
    _content = @"";
    _level = 0;
    _evaluateId = @"";
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasTime) {
    [output writeInt64:1 value:self.time];
  }
  if (self.hasUserId) {
    [output writeString:2 value:self.userId];
  }
  if (self.hasUserName) {
    [output writeString:3 value:self.userName];
  }
  if (self.hasHeadIconUrl) {
    [output writeString:4 value:self.headIconUrl];
  }
  if (self.hasUserLevel) {
    [output writeInt32:5 value:self.userLevel];
  }
  if (self.hasRentCategoryName) {
    [output writeString:6 value:self.rentCategoryName];
  }
  if (self.hasContent) {
    [output writeString:7 value:self.content];
  }
  [self.imageUrls enumerateObjectsUsingBlock:^(NSString *element, NSUInteger idx, BOOL *stop) {
    [output writeString:8 value:element];
  }];
  if (self.hasLevel) {
    [output writeInt32:9 value:self.level];
  }
  if (self.hasEvaluateId) {
    [output writeString:10 value:self.evaluateId];
  }
  [self.evaluateReplyInfo enumerateObjectsUsingBlock:^(EvaluateReplyInfo *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:11 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasTime) {
    size_ += computeInt64Size(1, self.time);
  }
  if (self.hasUserId) {
    size_ += computeStringSize(2, self.userId);
  }
  if (self.hasUserName) {
    size_ += computeStringSize(3, self.userName);
  }
  if (self.hasHeadIconUrl) {
    size_ += computeStringSize(4, self.headIconUrl);
  }
  if (self.hasUserLevel) {
    size_ += computeInt32Size(5, self.userLevel);
  }
  if (self.hasRentCategoryName) {
    size_ += computeStringSize(6, self.rentCategoryName);
  }
  if (self.hasContent) {
    size_ += computeStringSize(7, self.content);
  }
  {
    __block SInt32 dataSize = 0;
    const NSUInteger count = self.imageUrls.count;
    [self.imageUrls enumerateObjectsUsingBlock:^(NSString *element, NSUInteger idx, BOOL *stop) {
      dataSize += computeStringSizeNoTag(element);
    }];
    size_ += dataSize;
    size_ += (SInt32)(1 * count);
  }
  if (self.hasLevel) {
    size_ += computeInt32Size(9, self.level);
  }
  if (self.hasEvaluateId) {
    size_ += computeStringSize(10, self.evaluateId);
  }
  [self.evaluateReplyInfo enumerateObjectsUsingBlock:^(EvaluateReplyInfo *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(11, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ProductEvaluateInfo*) parseFromData:(NSData*) data {
  ProductEvaluateInfo* result = [[ProductEvaluateInfo alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"time", [NSNumber numberWithLongLong:self.time]];
  }
  if (self.hasUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userId", self.userId];
  }
  if (self.hasUserName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userName", self.userName];
  }
  if (self.hasHeadIconUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"headIconUrl", self.headIconUrl];
  }
  if (self.hasUserLevel) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userLevel", [NSNumber numberWithInteger:self.userLevel]];
  }
  if (self.hasRentCategoryName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"rentCategoryName", self.rentCategoryName];
  }
  if (self.hasContent) {
    [output appendFormat:@"%@%@: %@\n", indent, @"content", self.content];
  }
  [self.imageUrls enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@: %@\n", indent, @"imageUrls", obj];
  }];
  if (self.hasLevel) {
    [output appendFormat:@"%@%@: %@\n", indent, @"level", [NSNumber numberWithInteger:self.level]];
  }
  if (self.hasEvaluateId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"evaluateId", self.evaluateId];
  }
  [self.evaluateReplyInfo enumerateObjectsUsingBlock:^(EvaluateReplyInfo *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"evaluateReplyInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setTime:(SInt64) value {
  _hasTime = YES;
  _time = value;
}
- (void) setUserId:(NSString*) value {
  _hasUserId = YES;
  _userId = value;
}
- (void) setUserName:(NSString*) value {
  _hasUserName = YES;
  _userName = value;
}
- (void) setHeadIconUrl:(NSString*) value {
  _hasHeadIconUrl = YES;
  _headIconUrl = value;
}
- (void) setUserLevel:(SInt32) value {
  _hasUserLevel = YES;
  _userLevel = value;
}
- (void) setRentCategoryName:(NSString*) value {
  _hasRentCategoryName = YES;
  _rentCategoryName = value;
}
- (void) setContent:(NSString*) value {
  _hasContent = YES;
  _content = value;
}
- (void)setImageUrlsArray:(NSArray *)array {
  _imageUrls = [[NSMutableArray alloc] initWithArray:array];
}
- (void)addImageUrls:(NSString*)value {
  if (_imageUrls == nil) {
    _imageUrls = [[NSMutableArray alloc]init];
  }
  [_imageUrls addObject:value];
}
- (void) setLevel:(SInt32) value {
  _hasLevel = YES;
  _level = value;
}
- (void) setEvaluateId:(NSString*) value {
  _hasEvaluateId = YES;
  _evaluateId = value;
}
- (void)setEvaluateReplyInfoArray:(NSArray *)array {
  _evaluateReplyInfo = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addEvaluateReplyInfo:(EvaluateReplyInfo*)value {
  if (_evaluateReplyInfo == nil) {
    _evaluateReplyInfo = [[NSMutableArray alloc]init];
  }
  [_evaluateReplyInfo addObject:value];
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 8: {
        [self setTime:[input readInt64]];
        break;
      }
      case 18: {
        [self setUserId:[input readString]];
        break;
      }
      case 26: {
        [self setUserName:[input readString]];
        break;
      }
      case 34: {
        [self setHeadIconUrl:[input readString]];
        break;
      }
      case 40: {
        [self setUserLevel:[input readInt32]];
        break;
      }
      case 50: {
        [self setRentCategoryName:[input readString]];
        break;
      }
      case 58: {
        [self setContent:[input readString]];
        break;
      }
      case 66: {
        [self addImageUrls:[input readString]];
        break;
      }
      case 72: {
        [self setLevel:[input readInt32]];
        break;
      }
      case 82: {
        [self setEvaluateId:[input readString]];
        break;
      }
      case 90: {
        EvaluateReplyInfo* sub = [[EvaluateReplyInfo alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addEvaluateReplyInfo:sub];
        break;
      }
    }
  }
}
@end


@implementation EvaluateReplyInfo

- (instancetype) init {
  if ((self = [super init])) {
    _replyId = @"";
    _content = @"";
    _time = 0L;
    _fromMechant = NO;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasReplyId) {
    [output writeString:1 value:self.replyId];
  }
  if (self.hasContent) {
    [output writeString:2 value:self.content];
  }
  if (self.hasTime) {
    [output writeInt64:3 value:self.time];
  }
  if (self.hasFromMechant) {
    [output writeBool:4 value:self.fromMechant];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasReplyId) {
    size_ += computeStringSize(1, self.replyId);
  }
  if (self.hasContent) {
    size_ += computeStringSize(2, self.content);
  }
  if (self.hasTime) {
    size_ += computeInt64Size(3, self.time);
  }
  if (self.hasFromMechant) {
    size_ += computeBoolSize(4, self.fromMechant);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (EvaluateReplyInfo*) parseFromData:(NSData*) data {
  EvaluateReplyInfo* result = [[EvaluateReplyInfo alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasReplyId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"replyId", self.replyId];
  }
  if (self.hasContent) {
    [output appendFormat:@"%@%@: %@\n", indent, @"content", self.content];
  }
  if (self.hasTime) {
    [output appendFormat:@"%@%@: %@\n", indent, @"time", [NSNumber numberWithLongLong:self.time]];
  }
  if (self.hasFromMechant) {
    [output appendFormat:@"%@%@: %@\n", indent, @"fromMechant", [NSNumber numberWithBool:self.fromMechant]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setReplyId:(NSString*) value {
  _hasReplyId = YES;
  _replyId = value;
}
- (void) setContent:(NSString*) value {
  _hasContent = YES;
  _content = value;
}
- (void) setTime:(SInt64) value {
  _hasTime = YES;
  _time = value;
}
- (void) setFromMechant:(BOOL) value {
  _hasFromMechant = YES;
  _fromMechant = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setReplyId:[input readString]];
        break;
      }
      case 18: {
        [self setContent:[input readString]];
        break;
      }
      case 24: {
        [self setTime:[input readInt64]];
        break;
      }
      case 32: {
        [self setFromMechant:[input readBool]];
        break;
      }
    }
  }
}
@end


@implementation GetProductEvaluateListRequest

- (instancetype) init {
  if ((self = [super init])) {
    _productId = @"";
    _evaluateType = 0;
    _startIndex = 0;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasProductId) {
    [output writeString:1 value:self.productId];
  }
  if (self.hasEvaluateType) {
    [output writeInt32:2 value:self.evaluateType];
  }
  if (self.hasStartIndex) {
    [output writeInt32:3 value:self.startIndex];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasProductId) {
    size_ += computeStringSize(1, self.productId);
  }
  if (self.hasEvaluateType) {
    size_ += computeInt32Size(2, self.evaluateType);
  }
  if (self.hasStartIndex) {
    size_ += computeInt32Size(3, self.startIndex);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GetProductEvaluateListRequest*) parseFromData:(NSData*) data {
  GetProductEvaluateListRequest* result = [[GetProductEvaluateListRequest alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasProductId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"productId", self.productId];
  }
  if (self.hasEvaluateType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"evaluateType", [NSNumber numberWithInteger:self.evaluateType]];
  }
  if (self.hasStartIndex) {
    [output appendFormat:@"%@%@: %@\n", indent, @"startIndex", [NSNumber numberWithInteger:self.startIndex]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setProductId:(NSString*) value {
  _hasProductId = YES;
  _productId = value;
}
- (void) setEvaluateType:(SInt32) value {
  _hasEvaluateType = YES;
  _evaluateType = value;
}
- (void) setStartIndex:(SInt32) value {
  _hasStartIndex = YES;
  _startIndex = value;
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setProductId:[input readString]];
        break;
      }
      case 16: {
        [self setEvaluateType:[input readInt32]];
        break;
      }
      case 24: {
        [self setStartIndex:[input readInt32]];
        break;
      }
    }
  }
}
@end


@implementation GetProductEvaluateListResult

- (instancetype) init {
  if ((self = [super init])) {
    _resultCode = @"";
    _resultMsg = @"";
    _maxIndex = 0;
    _hasMore = NO;
    _totalCount = 0L;
    _totalImageCount = 0L;
  }
  return self;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasResultCode) {
    [output writeString:1 value:self.resultCode];
  }
  if (self.hasResultMsg) {
    [output writeString:2 value:self.resultMsg];
  }
  if (self.hasMaxIndex) {
    [output writeInt32:3 value:self.maxIndex];
  }
  if (self.hasHasMore) {
    [output writeBool:4 value:self.hasMore];
  }
  if (self.hasTotalCount) {
    [output writeInt64:5 value:self.totalCount];
  }
  if (self.hasTotalImageCount) {
    [output writeInt64:6 value:self.totalImageCount];
  }
  [self.productEvaluateInfo enumerateObjectsUsingBlock:^(ProductEvaluateInfo *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:7 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;

  size_ = 0;
  if (self.hasResultCode) {
    size_ += computeStringSize(1, self.resultCode);
  }
  if (self.hasResultMsg) {
    size_ += computeStringSize(2, self.resultMsg);
  }
  if (self.hasMaxIndex) {
    size_ += computeInt32Size(3, self.maxIndex);
  }
  if (self.hasHasMore) {
    size_ += computeBoolSize(4, self.hasMore);
  }
  if (self.hasTotalCount) {
    size_ += computeInt64Size(5, self.totalCount);
  }
  if (self.hasTotalImageCount) {
    size_ += computeInt64Size(6, self.totalImageCount);
  }
  [self.productEvaluateInfo enumerateObjectsUsingBlock:^(ProductEvaluateInfo *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(7, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GetProductEvaluateListResult*) parseFromData:(NSData*) data {
  GetProductEvaluateListResult* result = [[GetProductEvaluateListResult alloc] init];
  [result mergeFromData:data];  return result;
}
#ifdef DEBUG
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasResultCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultCode", self.resultCode];
  }
  if (self.hasResultMsg) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resultMsg", self.resultMsg];
  }
  if (self.hasMaxIndex) {
    [output appendFormat:@"%@%@: %@\n", indent, @"maxIndex", [NSNumber numberWithInteger:self.maxIndex]];
  }
  if (self.hasHasMore) {
    [output appendFormat:@"%@%@: %@\n", indent, @"hasMore", [NSNumber numberWithBool:self.hasMore]];
  }
  if (self.hasTotalCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"totalCount", [NSNumber numberWithLongLong:self.totalCount]];
  }
  if (self.hasTotalImageCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"totalImageCount", [NSNumber numberWithLongLong:self.totalImageCount]];
  }
  [self.productEvaluateInfo enumerateObjectsUsingBlock:^(ProductEvaluateInfo *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"productEvaluateInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
#endif
- (void) setResultCode:(NSString*) value {
  _hasResultCode = YES;
  _resultCode = value;
}
- (void) setResultMsg:(NSString*) value {
  _hasResultMsg = YES;
  _resultMsg = value;
}
- (void) setMaxIndex:(SInt32) value {
  _hasMaxIndex = YES;
  _maxIndex = value;
}
- (void) setHasMore:(BOOL) value {
  _hasHasMore = YES;
  _hasMore = value;
}
- (void) setTotalCount:(SInt64) value {
  _hasTotalCount = YES;
  _totalCount = value;
}
- (void) setTotalImageCount:(SInt64) value {
  _hasTotalImageCount = YES;
  _totalImageCount = value;
}
- (void)setProductEvaluateInfoArray:(NSArray *)array {
  _productEvaluateInfo = [[NSMutableArray alloc]initWithArray:array];
}
- (void)addProductEvaluateInfo:(ProductEvaluateInfo*)value {
  if (_productEvaluateInfo == nil) {
    _productEvaluateInfo = [[NSMutableArray alloc]init];
  }
  [_productEvaluateInfo addObject:value];
}
- (void) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields_ = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields_ build]];
        return ;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields_ extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields_ build]];
          return ;
        }
        break;
      }
      case 10: {
        [self setResultCode:[input readString]];
        break;
      }
      case 18: {
        [self setResultMsg:[input readString]];
        break;
      }
      case 24: {
        [self setMaxIndex:[input readInt32]];
        break;
      }
      case 32: {
        [self setHasMore:[input readBool]];
        break;
      }
      case 40: {
        [self setTotalCount:[input readInt64]];
        break;
      }
      case 48: {
        [self setTotalImageCount:[input readInt64]];
        break;
      }
      case 58: {
        ProductEvaluateInfo* sub = [[ProductEvaluateInfo alloc] init];
        [input readQJMessage:sub extensionRegistry:extensionRegistry];
        [self addProductEvaluateInfo:sub];
        break;
      }
    }
  }
}
@end


