// Code generated by Wire-Lite protocol buffer compiler, do not edit.
// Source file: ///home/admin/protobuf/src/b034d5a3fa893e050c91234030ec228e/proto/Notify
package com.qjoy.basjoo.core.model.pb;

import com.squareup.wire.Message;

/**
 * 获取通知
 */
public final class GetNotifyRequest extends Message {


  public GetNotifyRequest(GetNotifyRequest message) {
    super(message);
  }

  public GetNotifyRequest() {
  }

  public GetNotifyRequest fillTagValue(int tag, Object value) {
    switch(tag) {
        default: break;
        };
    return this;
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof GetNotifyRequest;
  }

  @Override
  public int hashCode() {
    return 0;
  }
}
