// Code generated by Wire-Lite protocol buffer compiler, do not edit.
// Source file: ///home/admin/protobuf/src/206a57347befe04d973320f9bd7aa135/proto/Refund
package com.qjoy.basjoo.core.model.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 获取退款详情
 */
public final class GetRefundDetailRequest extends Message {

  public static final int TAG_USERID = 1;
  public static final int TAG_ORDERID = 2;

  public static final String DEFAULT_USERID = "";
  public static final String DEFAULT_ORDERID = "";

  /**
   * 用户ID
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public String userId;

  /**
   * 订单ID
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public String orderId;

  public GetRefundDetailRequest(GetRefundDetailRequest message) {
    super(message);
    if (message == null) return;
    this.userId = message.userId;
    this.orderId = message.orderId;
  }

  public GetRefundDetailRequest() {
  }

  public GetRefundDetailRequest fillTagValue(int tag, Object value) {
    switch(tag) {
        case TAG_USERID:
        this.userId = (String)value;
        break;
        case TAG_ORDERID:
        this.orderId = (String)value;
        break;
        default: break;
        };
    return this;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetRefundDetailRequest)) return false;
    GetRefundDetailRequest o = (GetRefundDetailRequest) other;
    return equals(userId, o.userId)
        && equals(orderId, o.orderId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userId != null ? userId.hashCode() : 0;
      result = result * 37 + (orderId != null ? orderId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }
}
