// Code generated by Wire-Lite protocol buffer compiler, do not edit.
// Source file: ///home/admin/protobuf/src/c4f15da2f62eb9b901416c5f0208e221/proto/ResourceUpload
package com.qjoy.basjoo.core.model.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 资源上传请求
 */
public final class ResourceUploadRequest extends Message {

  public static final int TAG_BIZSCENE = 1;
  public static final int TAG_RESOURCETYPE = 2;
  public static final int TAG_CONTENT = 3;

  public static final String DEFAULT_BIZSCENE = "";
  public static final String DEFAULT_RESOURCETYPE = "";
  public static final String DEFAULT_CONTENT = "";

  /**
   * 业务场景
   */
  @ProtoField(tag = 1, type = STRING)
  public String bizScene;

  /**
   * 资源类型
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public String resourceType;

  /**
   * 资源内容 byte[] 转 String
   */
  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public String content;

  public ResourceUploadRequest(ResourceUploadRequest message) {
    super(message);
    if (message == null) return;
    this.bizScene = message.bizScene;
    this.resourceType = message.resourceType;
    this.content = message.content;
  }

  public ResourceUploadRequest() {
  }

  public ResourceUploadRequest fillTagValue(int tag, Object value) {
    switch(tag) {
        case TAG_BIZSCENE:
        this.bizScene = (String)value;
        break;
        case TAG_RESOURCETYPE:
        this.resourceType = (String)value;
        break;
        case TAG_CONTENT:
        this.content = (String)value;
        break;
        default: break;
        };
    return this;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ResourceUploadRequest)) return false;
    ResourceUploadRequest o = (ResourceUploadRequest) other;
    return equals(bizScene, o.bizScene)
        && equals(resourceType, o.resourceType)
        && equals(content, o.content);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = bizScene != null ? bizScene.hashCode() : 0;
      result = result * 37 + (resourceType != null ? resourceType.hashCode() : 0);
      result = result * 37 + (content != null ? content.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }
}
