CREATE TABLE `order_info` (
  `order_id` varchar(32) NOT NULL COMMENT '订单ID',
  `user_id` varchar(64) NOT NULL COMMENT '用户ID',
  `order_status` bigint(20) NOT NULL COMMENT '订单状态',
  `rent_start_time` timestamp NULL DEFAULT NULL COMMENT '起租起始时间',
  `rent_end_time` timestamp NULL DEFAULT NULL COMMENT '起租结束时间',
  `rent_days` bigint(20) DEFAULT NULL COMMENT '租用天数',
  `rent_count` bigint(20) DEFAULT NULL COMMENT '租用件数',
  `rent_fee` double(9,2) DEFAULT NULL COMMENT '租金总价',
  `pledge_fee` double(9,2) DEFAULT NULL COMMENT '押金',
  `transport_fee` double(9,2) DEFAULT NULL COMMENT '运费',
  `total_fee` double(9,2) DEFAULT NULL COMMENT '总费用',
  `transport_id` varchar(64) DEFAULT NULL COMMENT '物流ID',
  `evaluate_status` bigint(20) NOT NULL COMMENT '评价状态',
  `product_id` varchar(64) NOT NULL COMMENT '产品ID',
  `main_image_url` varchar(256) NOT NULL COMMENT '产品图片',
  `order_desc` varchar(256) NOT NULL COMMENT '订单描述',
  `category_code` varchar(256) NOT NULL COMMENT '产品类目code',
  `category_name` varchar(256) NOT NULL COMMENT '产品类目名称',
  `pay_time` timestamp NULL DEFAULT NULL COMMENT '支付时间',
  `pay_status` bigint(20) DEFAULT NULL COMMENT '支付状态',
  `pay_channel` bigint(20) DEFAULT NULL COMMENT '订单支付渠道',
  `pay_id` varchar(64) DEFAULT NULL COMMENT '支付ID',
  `delivery_time` timestamp NULL DEFAULT NULL COMMENT '发货时间',
  `receive_time` timestamp NULL DEFAULT NULL COMMENT '收货时间',
  `revert_time` timestamp NULL DEFAULT NULL COMMENT '归还时间',
  `refund_time` timestamp NULL DEFAULT NULL COMMENT '退款时间',
  `refund_fee` double(9,2) DEFAULT NULL COMMENT '退款金额',
  `refund_reason` varchar(256) DEFAULT NULL COMMENT '退款理由',
  `refund_intro` varchar(512) DEFAULT NULL COMMENT '退款说明',
  `complete_time` timestamp NULL DEFAULT NULL COMMENT '成交时间',
  `close_time` timestamp NULL DEFAULT NULL COMMENT '关闭时间',
  `vouchers` varchar(512) DEFAULT NULL COMMENT '使用的券信息',
  `address_id` varchar(64) DEFAULT NULL COMMENT '收货地址ID',
  `address_detail` varchar(512) DEFAULT NULL COMMENT '收货地址信息',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `valid_status` bigint(20) DEFAULT NULL COMMENT '有效状态',
  `recycle_status` bigint(20) DEFAULT NULL COMMENT '回收状态',
  `gmt_create` timestamp NULL DEFAULT NULL,
  `gmt_modify` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  KEY `user_id_index` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
