CREATE TABLE `user_info` (
  `user_id` varchar(64) NOT NULL,
  `login_id` varchar(64) DEFAULT NULL,
  `user_type` bigint(20) DEFAULT NULL,
  `user_status` bigint(20) DEFAULT NULL,
  `user_name` varchar(64) DEFAULT NULL,
  `mobile_no` varchar(32) DEFAULT NULL,
  `nick_name` varchar(64) DEFAULT NULL,
  `email` varchar(64) DEFAULT NULL,
  `cert_no` varchar(128) DEFAULT NULL,
  `cert_type` varchar(128) DEFAULT NULL,
  `cert_valid_begin` timestamp NULL DEFAULT NULL,
  `cert_valid_end` timestamp NULL DEFAULT NULL,
  `password` varchar(64) NULL DEFAULT,
  `payment_password` varchar(64) DEFAULT NULL,
  `gmt_register` timestamp NULL DEFAULT NULL,
  `last_login_ip` varchar(64) DEFAULT NULL,
  `last_login_time` timestamp NULL DEFAULT NULL,
  `real_name_status` bigint(20) DEFAULT NULL,
  `active_status` bigint(20) DEFAULT NULL,
  `head_icon_url` varchar(256) DEFAULT NULL,
  `source` varchar(64) DEFAULT NULL,
  `gmt_create` timestamp NULL DEFAULT NULL,
  `gmt_modify` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  KEY `login_id_index` (`login_id`),
  KEY `mobile_no_index` (`mobile_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
