// Code generated by Wire-Lite protocol buffer compiler, do not edit.
// Source file: ///home/admin/protobuf/src/3b364368d3c081841ba4e1f688208770/proto/Topic
package com.qjoy.basjoo.core.model.pb;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class TopicPraiseUser extends Message {

  public static final int TAG_USERID = 1;
  public static final int TAG_USERNICKNAME = 2;
  public static final int TAG_HEADICONURL = 3;
  public static final int TAG_PRAISETIME = 4;

  public static final String DEFAULT_USERID = "";
  public static final String DEFAULT_USERNICKNAME = "";
  public static final String DEFAULT_HEADICONURL = "";
  public static final Long DEFAULT_PRAISETIME = 0L;

  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public String userId;

  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public String userNickName;

  @ProtoField(tag = 3, type = STRING, label = REQUIRED)
  public String headIconUrl;

  @ProtoField(tag = 4, type = INT64, label = REQUIRED)
  public Long praiseTime;

  public TopicPraiseUser(TopicPraiseUser message) {
    super(message);
    if (message == null) return;
    this.userId = message.userId;
    this.userNickName = message.userNickName;
    this.headIconUrl = message.headIconUrl;
    this.praiseTime = message.praiseTime;
  }

  public TopicPraiseUser() {
  }

  public TopicPraiseUser fillTagValue(int tag, Object value) {
    switch(tag) {
        case TAG_USERID:
        this.userId = (String)value;
        break;
        case TAG_USERNICKNAME:
        this.userNickName = (String)value;
        break;
        case TAG_HEADICONURL:
        this.headIconUrl = (String)value;
        break;
        case TAG_PRAISETIME:
        this.praiseTime = (Long)value;
        break;
        default: break;
        };
    return this;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TopicPraiseUser)) return false;
    TopicPraiseUser o = (TopicPraiseUser) other;
    return equals(userId, o.userId)
        && equals(userNickName, o.userNickName)
        && equals(headIconUrl, o.headIconUrl)
        && equals(praiseTime, o.praiseTime);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userId != null ? userId.hashCode() : 0;
      result = result * 37 + (userNickName != null ? userNickName.hashCode() : 0);
      result = result * 37 + (headIconUrl != null ? headIconUrl.hashCode() : 0);
      result = result * 37 + (praiseTime != null ? praiseTime.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }
}
